export default [
    {
        title: 'Verbs',
        words: [
            { hiragana: 'はなします', translation: 'Говорить', kanji: '話します' },
            { hiragana: 'わかります', translation: 'Понимать', kanji: '分かります' },
            { hiragana: 'しります', translation: 'Знать', kanji: '知ります' },
            { hiragana: 'のみます', translation: 'Пить', kanji: '飲みます' },
            { hiragana: 'みます', translation: 'Смотреть', kanji: '見ます' },
            { hiragana: 'つかいます', translation: 'Использовать', kanji: '使います' },
            { hiragana: 'とります', translation: 'Фотографировать', kanji: '撮ります' },
            { hiragana: 'あいます', translation: 'Встретить', kanji: '会います' },
            { hiragana: 'いきます', translation: 'Идти', kanji: '行きます' },
            { hiragana: 'まちます', translation: 'Ждать', kanji: '待ちます' },
            { hiragana: 'のります', translation: 'Зайти в поезд, автобус', kanji: '乗ります' },
            { hiragana: 'します', translation: 'Делать', kanji: '為ます' },
            { hiragana: 'きます', translation: 'Приходить', kanji: '来ます' },
            { hiragana: 'はじまります', translation: 'Начинается', kanji: '始まります' },
            { hiragana: 'きんちょうします', translation: 'Нервничать', kanji: '緊張します' },
            { hiragana: 'わすれます', translation: 'Забывать', kanji: '忘れます' },
            { hiragana: 'しんぱいします', translation: 'Беспокоиться', kanji: '心配します' },
            { hiragana: 'もうします', translation: 'Называйте меня', kanji: '申します' },
            { hiragana: 'よみます', translation: 'Читать', kanji: '読みます' },
            { hiragana: 'かいます', translation: 'Покупать', kanji: '買います' },
            { hiragana: 'はらえます', translation: 'Платить', kanji: '払えます' },
            { hiragana: 'かきます', translation: 'Писать', kanji: '掻きます' },
            { hiragana: 'つけます', translation: 'Включить', kanji: '就けます' },
            { hiragana: 'けします', translation: 'Выключать', kanji: '消します' },
            { hiragana: 'ききます', translation: 'Слушать', kanji: '聞きます' },
            { hiragana: 'まがります', translation: 'Поворачивать', kanji: '曲がります' },
            { hiragana: 'もらいます', translation: 'Принимать', kanji: '貰います' },
            { hiragana: 'おくります', translation: 'Отправлять', kanji: '送ります' },
            { hiragana: 'おします', translation: 'Толкать', kanji: '押します' },
            { hiragana: 'すいます', translation: 'Курить', kanji: '吸います' },
            { hiragana: 'つくります', translation: 'Производить, делать', kanji: '作ります' },
            { hiragana: 'うります', translation: 'Продавать', kanji: '売ります' },
            { hiragana: 'あげます', translation: 'Давать' },
            { hiragana: 'あけます', translation: 'Открывать', kanji: '空きます' },
            { hiragana: 'でます', translation: 'Оставлять, выходить', kanji: '出ます' },
            { hiragana: 'みせます', translation: 'Показывать', kanji: '見せます' },
            { hiragana: 'おります', translation: 'Выходить (из поезда)', kanji: '降ります' },
            { hiragana: 'おしえます', translation: 'Учить', kanji: '教えます' },
            { hiragana: 'しめます', translation: 'Закрывать', kanji: '閉めます' },
            { hiragana: 'とめます', translation: 'Остановиться, припарковаться', kanji: '止めます' },
            { hiragana: 'べんきょうします', translation: 'Учиться', kanji: '勉強します' },
            { hiragana: 'かえります', translation: 'Возвращаться', kanji: '帰りむす' },
            { hiragana: 'ささえます', translation: 'Поддерживать', kanji: '支えます' },
            { hiragana: 'おわります', translation: 'Заканчивать', kanji: '終わります' },
            { hiragana: 'おなかがすきます', translation: 'Быть голодным', kanji: 'お腹が空きます' },
            { hiragana: 'ぬぎます', translation: 'Раздеваться', kanji: '脱ぎます' },
            { hiragana: 'きかざります', translation: 'Одеваться', kanji: '着飾ります' },
            { hiragana: 'なります', translation: 'Становиться', kanji: '成ります' },
            { hiragana: 'ねます', translation: 'Ложиться спать' },
            { hiragana: 'まぜます', translation: 'Смешать', kanji: '交ぜます' },
            { hiragana: 'あるきます', translation: 'Ходить', kanji: '歩きます' },
            { hiragana: 'とびます', translation: 'Лететь', kanji: '飛びます' },
            { hiragana: 'わたります', translation: 'Пересекать', kanji: '渡ります' },
            { hiragana: 'だきしめます', translation: 'Обнимать', kanji: '抱きしめます' },
            { hiragana: 'しゅっぱつします', translation: 'Уходить', kanji: '出発します' },
            { hiragana: 'とうちゃくします', translation: 'Приезжать', kanji: '到着します' },
            { hiragana: 'つかれます', translation: 'Уставать', kanji: '疲れます' },
            { hiragana: 'えらびます', translation: 'Выбирать', kanji: '選びます' },
            { hiragana: 'きめます', translation: 'Решить (decide)', kanji: '決めます' },
            { hiragana: 'とまります', translation: 'Оставаться в', kanji: '泊まります' },
            { hiragana: 'およぎます', translation: 'Плавать', kanji: '泳ぎます' },
            { hiragana: 'のぼります', translation: 'Подниматься, забираться', kanji: '上ります' },
            { hiragana: 'たてます', translation: 'Строить', kanji: '建てます' },
            { hiragana: 'そそぎます', translation: 'Наполнить (водой)', kanji: '注ぎます' },
            { hiragana: 'あそびます', translation: 'Играть', kanji: '遊びます' },
            { hiragana: 'ぬります', translation: 'Рисовать', kanji: '塗ります' },
            { hiragana: 'さけびます', translation: 'Кричать', kanji: '叫びます' },
            { hiragana: 'かけます', translation: 'Звонить', kanji: '掛けます' },
            { hiragana: 'すみます', translation: 'Жить', kanji: '住みます' },
            { hiragana: 'おきます', translation: 'Просыпаться', kanji: '起きます' },
            { hiragana: 'おきます', translation: 'Положить', kanji: '置きます' },
            { hiragana: 'きります', translation: 'Резать', kanji: '切ります' },
            { hiragana: 'さきます', translation: 'Расцвести', kanji: '咲きます' },
            { hiragana: 'しょうたいします', translation: 'Пригласить', kanji: '招待します' },
            { hiragana: 'つかまえます', translation: 'Поймать', kanji: '捕まえます' },
            { hiragana: 'みつけます', translation: 'Найти', kanji: '見つけます' },
            { hiragana: 'おとします', translation: 'Уронить, падать', kanji: '落とします' },
            { hiragana: 'こたえます', translation: 'Отвечать', kanji: '答えます' },
            { hiragana: 'さわります', translation: 'Трогать', kanji: '触ります' },
            { hiragana: 'なくします', translation: 'Потерять', kanji: '無くします' },
            { hiragana: 'しにます', translation: 'Умереть', kanji: '死にます' },
            { hiragana: 'きえます', translation: 'Исчезнуть', kanji: '消えます' },
            { hiragana: 'うちます', translation: 'Бить, ударить', kanji: '打ちます' },
            { hiragana: 'まけます', translation: 'Проиграть', kanji: '負けます' },
            { hiragana: 'こわれます', translation: 'Сломать', kanji: '壊れます' },
            { hiragana: 'やきます', translation: 'Печь', kanji: '焼きます' },
            { hiragana: 'さがします', translation: 'Искать', kanji: '探します' },
            { hiragana: 'かわります', translation: 'Менять', kanji: '変わります' },
            { hiragana: 'いのります', translation: 'Молиться, желать', kanji: '祈ります' },
            { hiragana: 'ちかいます', translation: 'Клясться', kanji: '誓います' },
            { hiragana: 'とどきます', translation: 'Достичь', kanji: '届きます' },
            { hiragana: 'おどろきます', translation: 'Удивлять', kanji: '驚きます' },
            { hiragana: 'あたためます', translation: 'Согреть', kanji: '温めます' },
            { hiragana: 'おくれます', translation: 'Опоздать, задержаться', kanji: '遅れます' },
            { hiragana: 'ふざけます', translation: 'Шутить, насмехаться', kanji: '巫山戯ます' },
            { hiragana: 'かんがえます', translation: 'Думать', kanji: '考えます' },
            { hiragana: 'かぞえます', translation: 'Считать', kanji: '数えます' },
            { hiragana: 'そうじします', translation: 'Чистить', kanji: '掃除します' },
            { hiragana: 'ふきます', translation: 'Протирать', kanji: '拭きます' },
            { hiragana: 'うたいます', translation: 'Петь', kanji: '歌います' },
            { hiragana: 'なきます', translation: 'Плакать', kanji: '泣きます' },
            { hiragana: 'しんじます', translation: 'Верить', kanji: '信じます' },
            { hiragana: 'わらいます', translation: 'Смеяться', kanji: '笑います' },
            { hiragana: 'うまれます', translation: 'Родиться', kanji: '生まれます' },
            { hiragana: 'かかります', translation: 'Стоить, занять', kanji: 'かかります' },
            { hiragana: 'おぼえます', translation: 'Запомнить', kanji: '覚えます' },
            { hiragana: 'おぼれます', translation: 'Утонуть', kanji: '溺れます' },
            { hiragana: 'おごります', translation: 'Угощать', kanji: '奢ります' },
            { hiragana: 'ながれます', translation: 'Течь', kanji: '流れます' },
            { hiragana: 'にあいます', translation: 'Подходить (одежда и пр.)', kanji: '似合います' },
            { hiragana: 'わります', translation: 'Разделять', kanji: '割ります' },
            { hiragana: 'かぶります', translation: 'Одевать, носить', kanji: '被ぶります' }
        ]
    },
    {
        title: 'Nouns',
        words: [
            { hiragana: 'めんきょ', translation: 'Лицензия, уроки', kanji: '免許' },
            { hiragana: 'うんてん', translation: 'Вождение', kanji: '運転' },
            { hiragana: 'うんてんしゅ', translation: 'Водитель', kanji: '運転手' },
            { hiragana: 'しゃしん', translation: 'Фото', kanji: '写真' },
            { hiragana: 'やさしい', translation: 'Доброжелательность' },
            { hiragana: 'けっこんしき', translation: 'Свадебная церемония', kanji: '結婚式' },
            { hiragana: 'おきゃくさん', translation: 'Посетитель, гость', kanji: 'お客さん' },
            { hiragana: 'てんいん', translation: 'Работник, клерк', kanji: '店員' },
            { hiragana: 'りょこう', translation: 'Поездка, путешествие', kanji: '旅行' },
            { hiragana: 'たいざい', translation: 'Пребывание', kanji: '滞在' },
            { hiragana: 'もくてき', translation: 'Цель', kanji: '目的' },
            { hiragana: 'きかん', translation: 'Продолжительность', kanji: '期間' },
            { hiragana: 'たいざいきかん', translation: 'Продолжительность пребывания' },
            { hiragana: 'たいざいもくてき', translation: 'Цель пребывания' },
            { hiragana: 'かんこう', translation: 'Осмотр достопримечательностей', kanji: '観光' },
            { hiragana: 'よてい', translation: 'План', kanji: '予定' },
            { hiragana: 'もの', translation: 'Вещь', kanji: '物' },
            { hiragana: 'うち', translation: 'Дом, моя семья, моя', kanji: '家' },
            { hiragana: 'うそつき', translation: 'Лжец', kanji: '嘘つき' },
            { hiragana: 'おさけ', translation: 'Алкоголь', kanji: 'お酒' },
            { hiragana: 'りょうり', translation: 'Еда', kanji: '料理' },
            { hiragana: 'まち', translation: 'Город', kanji: '町' },
            { hiragana: 'くに', translation: 'Страна', kanji: '国' },
            { hiragana: 'まくら', translation: 'Подушка', kanji: '枕' },
            { hiragana: 'かばん', translation: 'Сумка', kanji: '鞄' },
            { hiragana: 'ぼうし', translation: 'Шляпа', kanji: '帽子' },
            { hiragana: 'てんき', translation: 'Погода', kanji: '天気' },
            { hiragana: 'いい、よくない', translation: 'Хороший, нехороший' },
            { hiragana: 'ほんとう', translation: 'Правда', kanji: '本当' },
            { hiragana: 'うそ', translation: 'Ложь', kanji: '嘘' },
            { hiragana: 'しんぶん', translation: 'Газета', kanji: '新聞' },
            { hiragana: 'どうぶつえん', translation: 'Зоопарк', kanji: '動物園' },
            { hiragana: 'どうぶつ', translation: 'Животное', kanji: '動物' },
            { hiragana: 'おんがく', translation: 'Музыка', kanji: '音楽' },
            { hiragana: 'へや', translation: 'Комната', kanji: '部屋' },
            { hiragana: 'いす', translation: 'Стул', kanji: '椅子' },
            { hiragana: 'ひこうき', translation: 'Самолёт, рейс', kanji: '飛行機' },
            { hiragana: 'おみやげ', translation: 'Сувенир', kanji: 'お土産' },
            { hiragana: 'おと', translation: 'Звук', kanji: '音' },
            { hiragana: 'しゃこ', translation: 'Гараж', kanji: '車庫' },
            { hiragana: 'ちかてつ', translation: 'Метро', kanji: '地下鉄' },
            { hiragana: 'さいしゅう', translation: 'Последний', kanji: '最終' },
            { hiragana: 'しゅうでん', translation: 'Последний поезд', kanji: '終電' },
            { hiragana: 'ふくしゅう', translation: 'Месть', kanji: '復讐' },
            { hiragana: 'まちがい', translation: 'Ошибка', kanji: '間違い' },
            { hiragana: 'ぐうぜん', translation: 'Совпадение', kanji: '偶然' },
            { hiragana: 'じっか', translation: 'Родительский дом', kanji: '実家' },
            { hiragana: 'きず', translation: 'Царапина', kanji: '傷' },
            { hiragana: 'ようじ', translation: 'Задачи', kanji: '用事' },
            { hiragana: 'ざっし', translation: 'Журнал', kanji: '雑誌' },
            { hiragana: 'おみせ', translation: 'Магазин', kanji: 'お店' },
            { hiragana: 'ちゅうもん', translation: 'Заказ', kanji: '注文' },
            { hiragana: 'しゅっぱつ', translation: 'Выезд', kanji: '出発' },
            { hiragana: 'とうちゃく', translation: 'Приезд', kanji: '到着' },
            { hiragana: 'にもつ', translation: 'Багаж', kanji: '荷物' },
            { hiragana: 'ちず', translation: 'Карта', kanji: '地図' },
            { hiragana: 'てら', translation: 'Храм', kanji: '寺' },
            { hiragana: 'ところ', translation: 'Место', kanji: '所' },
            { hiragana: 'きょうみ', translation: 'Интерес', kanji: '興味' },
            { hiragana: 'におい', translation: 'Запах', kanji: '匂い' },
            { hiragana: 'あじ', translation: 'Вкус', kanji: '味' },
            { hiragana: 'しあわせ', translation: 'Счастье', kanji: '幸せ' },
            { hiragana: 'つくえ', translation: 'Парта', kanji: '机' },
            { hiragana: 'いろ', translation: 'Цвет', kanji: '色' },
            { hiragana: 'てがみ', translation: 'Письмо', kanji: '手紙' },
            { hiragana: 'かんがえ', translation: 'Мысль', kanji: '考え' },
            { hiragana: 'ゆかた', translation: 'Кимоно', kanji: '浴衣' },
            { hiragana: 'かしゅ', translation: 'Певец', kanji: '歌手' },
            { hiragana: 'おまつり', translation: 'Фестиваль', kanji: 'お祭り' },
            { hiragana: 'じんせい', translation: 'Жизнь', kanji: '人生' },
            { hiragana: 'みずうみ', translation: 'Озеро', kanji: '湖' },
            { hiragana: 'ゆめ', translation: 'Сон', kanji: '夢' },
            { hiragana: 'じゅうしょ', translation: 'Адрес', kanji: '住所' },
            { hiragana: 'かわ', translation: 'Река, кожа', kanji: '川' },
            { hiragana: 'おかわり', translation: 'Добавка', kanji: 'お代わり' },
            { hiragana: 'かいだん', translation: 'Ступеньки', kanji: '階段' },
            { hiragana: 'きぼう', translation: 'Надежда', kanji: '希望' },
            { hiragana: 'れつ', translation: 'Очередь', kanji: '列' },
            { hiragana: 'さいこう', translation: 'Лучший', kanji: '最高' },
            { hiragana: 'さいてい', translation: 'Худший', kanji: '最低' },
            { hiragana: 'うわさ', translation: 'Слухи', kanji: '噂' },
            { hiragana: 'こじん', translation: 'Личный', kanji: '個人' },
            { hiragana: 'たな', translation: 'Полка', kanji: '棚' },
            { hiragana: 'かいもの', translation: 'Покупки', kanji: '買い物' },
            { hiragana: 'しあい', translation: 'Матч, игра', kanji: '試合' },
            { hiragana: 'しつもん', translation: 'Вопросы', kanji: '質問' },
            { hiragana: 'ふく', translation: 'Одежда', kanji: '服' },
            { hiragana: 'あかちゃん', translation: 'Грудничковый ребёнок', kanji: '赤ちゃん' },
            { hiragana: 'おいわい', translation: 'Поздравление', kanji: 'お祝い' },
            { hiragana: 'みらい', translation: 'Будущее', kanji: '未来' },
            { hiragana: 'じょうだん', translation: 'Шутка', kanji: '冗談' },
            { hiragana: 'はんぶん', translation: 'Половина', kanji: '半分' },
            { hiragana: 'にんき', translation: 'Популярность', kanji: '人気' },
            { hiragana: 'しんこう', translation: 'Вера, доверие', kanji: '信仰' },
            { hiragana: 'ひかり', translation: 'Свет', kanji: '光' },
            { hiragana: 'もと', translation: 'Происхождение, фундамент', kanji: '元' },
            { hiragana: 'じゅぎょう', translation: 'Урок', kanji: '授業' },
            { hiragana: 'ないしょ', translation: 'Секрет, тайна', kanji: '内緒' },
            { hiragana: 'しゅみ', translation: 'Хобби', kanji: '趣味' },
            { hiragana: 'ちから', translation: 'Сила', kanji: '力' },
            { hiragana: 'かぎ', translation: 'Ключ', kanji: '鍵' },
            { hiragana: 'おふろ', translation: 'Ванна', kanji: 'お風呂' },
            { hiragana: 'でんき', translation: 'Электричество, свет', kanji: '電気' },
            { hiragana: 'ごうしつ', translation: 'Счётчик для комнат', kanji: '号室' },
            { hiragana: 'かい', translation: 'Счётчик для происшествий', kanji: '回' },
            { hiragana: 'まい', translation: 'Счётчик для тонких плоских вещей', kanji: '枚' },
            { hiragana: 'めい', translation: 'Счётчик для людей', kanji: '名' },
            { hiragana: '～ぬき', translation: 'Постфикс для фразы "Без ... (чего-нибудь)"', kanji: '～抜き' },
            { hiragana: 'むし', translation: 'Насекомое', kanji: '虫' },
            { hiragana: 'はいります', translation: 'Войти, зайти в', kanji: '入ります' },
            { hiragana: 'つき', translation: 'Луна', kanji: '月' },
            { hiragana: 'うけつけ', translation: 'Ресепшен', kanji: '受付' },
            { hiragana: 'みず', translation: 'Вода', kanji: '水' },
            { hiragana: 'うた', translation: 'Песня', kanji: '歌' },
            { hiragana: 'かべ', translation: 'Стена', kanji: '壁' },
            { hiragana: 'ほこり', translation: 'Гордость', kanji: '誇り' },
            { hiragana: 'きっぷ', translation: 'Билет (поезд)', kanji: '切符' },
            { hiragana: 'じゆうせき', translation: 'Незарезервированные места (поезд)', kanji: '自由席' },
            { hiragana: 'していせき', translation: 'Зарезервированные места (поезд)', kanji: '指定席' },
            { hiragana: 'おとな', translation: 'Взрослый (человек)', kanji: '大人' },
            { hiragana: 'かふんしょう', translation: 'Аллергия на пыльцу', kanji: '花粉症' },
            { hiragana: 'ほこり', translation: 'Грязь, пыль', kanji: '埃' },
            { hiragana: 'にわ', translation: 'Сад', kanji: '庭' },
            { hiragana: 'じこしょうかい', translation: 'Self introduction', kanji: '自己紹介' },
            { hiragana: 'あんない', translation: 'Информация, руководство', kanji: '案内' },
            { hiragana: 'よやく', translation: 'Бронирование, встреча', kanji: '予約' },
            { hiragana: 'ほけんしょう', translation: 'Страховая карта', kanji: '保険証' },
            { hiragana: 'かたち', translation: 'Форма', kanji: '形' },
            { hiragana: 'えいぎょう', translation: 'Бизнес, торговля, продажи', kanji: '営業' },
            { hiragana: 'はつおん', translation: 'Произношение', kanji: '発音' },
            { hiragana: 'れんらく', translation: 'Общение, контакт', kanji: '連絡' },
            { hiragana: 'わりかん', translation: 'Разделение стоимости', kanji: '割り勘' },
            { hiragana: 'おすすめ', translation: 'Рекоммендация', kanji: 'おすすめ' },
            { hiragana: 'まんなか', translation: 'Середина', kanji: '真ん中' },
            { hiragana: 'ちょうし', translation: 'Состояние', kanji: '調子' },
            { hiragana: 'こくせき', translation: 'Национальность', kanji: '国籍' },
            { hiragana: 'かがみ', translation: 'Зеркало', kanji: '鏡' },
            { hiragana: 'もんだい', translation: 'Проблема, вопрос', kanji: '問題' },
            { hiragana: 'しま', translation: 'Остров', kanji: '島' },
            { hiragana: 'いいわけ', translation: 'Оправдание', kanji: '言い訳' },
            { hiragana: 'さくひん', translation: 'Работа', kanji: '作品' },
            { hiragana: 'のろい', translation: 'Проклятье', kanji: '呪い' },
            { hiragana: 'しんさく', translation: 'Новая работа', kanji: '新作' }
        ]
    },
    {
        title: 'Adjectives (い)',
        words: [
            { hiragana: 'ながい', translation: 'Длинный', kanji: '長い' },
            { hiragana: 'たかい', translation: 'Высокий', kanji: '高い' },
            { hiragana: 'みじかい', translation: 'Короткий', kanji: '短い' },
            { hiragana: 'つよい', translation: 'Сильный', kanji: '強い' },
            { hiragana: 'よわい', translation: 'Слабый', kanji: '弱い' },
            { hiragana: 'ちいさい', translation: 'Небольшой', kanji: '小さい' },
            { hiragana: 'おおきい', translation: 'Большой', kanji: '大きい' },
            { hiragana: 'はやい', translation: 'Быстрый', kanji: '速い' },
            { hiragana: 'かわいい', translation: 'Милый', kanji: '可愛い' },
            { hiragana: 'あまい', translation: 'Сладкий', kanji: '甘い' },
            { hiragana: 'わかい', translation: 'Молодой', kanji: '若い' },
            { hiragana: 'ふるい', translation: 'Старый', kanji: '古い' },
            { hiragana: 'つまらない', translation: 'Скучный', kanji: '詰らない' },
            { hiragana: 'おもい', translation: 'Тяжёлый', kanji: '重い' },
            { hiragana: 'ふつう', translation: 'Обычный', kanji: '普通' },
            { hiragana: 'あたらしい', translation: 'Новый', kanji: '新しい' },
            { hiragana: 'まっすぐ', translation: 'Прямой', kanji: '真っ直ぐ' },
            { hiragana: 'おなじ', translation: 'Такой же', kanji: '同じ' },
            { hiragana: 'すずしい', translation: 'Прохладый (о погоде)', kanji: '涼しい' },
            { hiragana: 'あたたかい', translation: 'Тёплый (о погоде)', kanji: '温かい' },
            { hiragana: 'やすい', translation: 'Дешёвый', kanji: '安い' },
            { hiragana: 'たのしい', translation: 'Весёлый', kanji: '楽しい' },
            { hiragana: 'おいしい', translation: 'Вкусный', kanji: '美味しい' },
            { hiragana: 'つめたい', translation: 'Холодный (на ощупь)', kanji: '冷たい' },
            { hiragana: 'いそがしい', translation: 'Занят', kanji: '忙しい' },
            { hiragana: 'ちかい', translation: 'Близкий', kanji: '近い' },
            { hiragana: 'とおい', translation: 'Далёкий', kanji: '遠い' },
            { hiragana: 'いたい', translation: 'Больно', kanji: '痛い' },
            { hiragana: 'おもしろい', translation: 'Интересный, забавный', kanji: '面白い' },
            { hiragana: 'ただしい', translation: 'Правильный', kanji: '正しい' },
            { hiragana: 'すっぱい', translation: 'Кислый', kanji: '酸っぱい' },
            { hiragana: 'にがい', translation: 'Горький', kanji: '苦い' },
            { hiragana: 'せまい', translation: 'Узкий', kanji: '狭い' },
            { hiragana: 'おそい', translation: 'Медленный, поздний', kanji: '遅い' },
            { hiragana: 'くらい', translation: 'Тёмный', kanji: '暗い' },
            { hiragana: 'きたない', translation: 'Грязный', kanji: '汚い' },
            { hiragana: 'かるい', translation: 'Светлый', kanji: '軽い' },
            { hiragana: 'からい', translation: 'Горячий, острый', kanji: '辛い' },
            { hiragana: 'ひろい', translation: 'Широкий', kanji: '広い' },
            { hiragana: 'ひくい', translation: 'Низкий', kanji: '低い' },
            { hiragana: 'あかるい', translation: 'Яркий', kanji: '明るい' },
            { hiragana: 'あぶない', translation: 'Опасный', kanji: '危ない' },
            { hiragana: 'わるい', translation: 'Плохой', kanji: '悪い' },
            { hiragana: 'ほそい', translation: 'Худой, тонкий', kanji: '細い' },
            { hiragana: 'ほしい', translation: 'Желаемый', kanji: '欲しい' },
            { hiragana: 'いっぱい', translation: 'Полный', kanji: '一杯' },
            { hiragana: 'こわい', translation: 'Страшный', kanji: '怖い' },
            { hiragana: 'むしあつい', translation: 'Влажный (погода)', kanji: '蒸し暑い' },
            { hiragana: 'ふかい', translation: 'Глубокий', kanji: '深い' },
            { hiragana: 'おとなしい', translation: 'Тихий', kanji: 'おとなしい' },
            { hiragana: 'しょっぱい', translation: 'Солёный', kanji: 'しょっぱい' },
            { hiragana: 'うつくしい', translation: 'Красивый', kanji: '美しい' },
            { hiragana: 'くだらない', translation: 'Бесполезный', kanji: '下らない' }
        ]
    },
    {
        title: 'Adjectives (な)',
        words: [
            { hiragana: 'きれい (な)', translation: 'Красивый', kanji: '綺麗 (な)' },
            { hiragana: 'しずか (な)', translation: 'Спокойный', kanji: '静か (な)' },
            { hiragana: 'とくべつ (な)', translation: 'Особенный', kanji: '特別 (な)' },
            { hiragana: 'かんたん (な)', translation: 'Простой', kanji: '簡単 (な)' },
            { hiragana: 'べんり (な)', translation: 'Удобный', kanji: '便利 (な)' },
            { hiragana: 'ふべん (な)', translation: 'Неудобный', kanji: '不便 (な)' },
            { hiragana: 'すてき (な)', translation: 'Хороший, фантастический', kanji: '素敵 (な)' },
            { hiragana: 'あんぜん (な)', translation: 'Безопасный', kanji: '安全 (な)' },
            { hiragana: 'だいじ (な)', translation: 'Важный', kanji: '大事 (な)' },
            { hiragana: 'だめ (な)', translation: 'Нехороший', kanji: '駄目 (な)' },
            { hiragana: 'ふしんせつ (な)', translation: 'Недобрый', kanji: '不親切 (な)' },
            { hiragana: 'げんき (な)', translation: 'Хороший', kanji: '元気 (な)' },
            { hiragana: 'じょうず (な)', translation: 'Умелый', kanji: '上手 (な)' },
            { hiragana: 'へた (な)', translation: 'Неумелый', kanji: '下手 (な)' },
            { hiragana: 'ひま (な)', translation: 'Свободный (время)', kanji: '暇 (な)' },
            { hiragana: 'いろいろ (な)', translation: 'Различный', kanji: '色々 (な)' },
            { hiragana: 'すき (な)', translation: 'Нравится', kanji: '好き (な)' },
            { hiragana: 'きらい (な)', translation: 'Несимпатичный (не нравится)', kanji: '嫌い (な)' },
            { hiragana: 'にぎやか (な)', translation: 'Живой', kanji: '賑やか (な)' },
            { hiragana: 'しんせつ (な)', translation: 'Добрый', kanji: '親切 (な)' },
            { hiragana: 'しつれい (な)', translation: 'Грубый', kanji: '失礼 (な)' },
            { hiragana: 'ゆうめい (な)', translation: 'Известный', kanji: '有名 (な)' },
            { hiragana: 'むり (な)', translation: 'Невозможный', kanji: '無理 (な)' },
            { hiragana: 'しょうじき (な)', translation: 'Честный', kanji: '正直 (な)' },
            { hiragana: 'しんせん (な)', translation: 'Свежий', kanji: '新鮮 (な)' },
            { hiragana: 'しんけん (な)', translation: 'Серьёзный', kanji: '真剣 (な)' },
            { hiragana: 'たいへん (な)', translation: 'Трудный, тяжёлый', kanji: '大変 (な)' },
            { hiragana: 'かわいそう (な)', translation: 'Бедный, жалкий', kanji: '可哀相 (な)' },
            { hiragana: 'おしゃれ (な)', translation: 'Стильный', kanji: '御洒落 (な)' },
            { hiragana: 'ていねい (な)', translation: 'Вежливый', kanji: '丁寧 (な)' },
            { hiragana: 'ぜっこうちょう (な)', translation: 'Восхитительный', kanji: '絶好調 (な)' },
            { hiragana: 'まあまあ (な)', translation: 'Так себе', kanji: 'まあまあ (な)' }
        ]
    },
    {
        title: 'Adverbs',
        words: [
            { hiragana: 'ちょっと', translation: 'Немного' },
            { hiragana: 'なんて', translation: 'Как (что-то)' },
            { hiragana: 'うれしい', translation: 'Рад' },
            { hiragana: 'また', translation: 'Также' },
            { hiragana: 'こんなふうに', translation: 'Также (like this)' },
            { hiragana: 'ちょうど', translation: 'Точно' },
            { hiragana: 'たぶん', translation: 'Вероятно, возможно' },
            { hiragana: 'でしょう', translation: 'Вероятно, возможно' },
            { hiragana: 'だけ', translation: 'Только' },
            { hiragana: 'もちろん', translation: 'Конечно', kanji: '勿論' },
            { hiragana: 'やさしく', translation: 'Осторожно' },
            { hiragana: 'あまり', translation: 'Не так много, чуть-чуть' },
            { hiragana: 'ぜんぜん', translation: 'Вовсе нет', kanji: '全然' },
            { hiragana: 'ぐらい', translation: 'Примерно (после подсчёта)', kanji: '位' },
            { hiragana: 'だいたい', translation: 'Примерно (перед подсчётом)' },
            { hiragana: 'あとで', translation: 'Позже, потом', kanji: '後で' },
            { hiragana: 'そして', translation: 'Потом' },
            { hiragana: 'むりょう', translation: 'Бесплатно', kanji: '無料' },
            { hiragana: 'だって', translation: 'Потому что' },
            { hiragana: 'まだ', translation: 'Всё ещё (still)' },
            { hiragana: 'たとえば', translation: 'Например' },
            { hiragana: 'たくさん', translation: 'Много' },
            { hiragana: 'ちょう', translation: 'Супер' },
            { hiragana: 'ぜったいに', translation: 'Определённо, безоговорочно' },
            { hiragana: 'おかしい', translation: 'Странно', kanji: '可笑しい' },
            { hiragana: 'そろそろ', translation: 'Медленно' },
            { hiragana: 'すぐ', translation: 'Немедленно' },
            { hiragana: 'まず', translation: 'Прежде всего' },
            { hiragana: 'じつは', translation: 'На самом деле', kanji: '実は' },
            { hiragana: 'いっしょに', translation: 'Вместе', kanji: '⼀緒に' },
            { hiragana: 'べつべつ', translation: 'Раздельно', kanji: '別々' },
            { hiragana: 'むかし', translation: 'Давно', kanji: '昔' },
            { hiragana: 'かわりに', translation: 'Вместо', kanji: '代わりに' },
            { hiragana: 'ぜんぶ', translation: 'Всё', kanji: '全部' },
            { hiragana: 'てづくり', translation: 'Ручной работы', kanji: '手作り' },
            { hiragana: 'めちゃめちゃ', translation: 'Очень, супер', kanji: 'めちゃめちゃ' },
            { hiragana: 'あいかわらず', translation: 'Как обычно', kanji: '相変わらず' },
            { hiragana: 'かなり', translation: 'Значительно', kanji: '可也' },
            { hiragana: 'なかなか', translation: 'Вполне, очень (превысит ваши ожидания)', kanji: 'なかなか' },
            { hiragana: 'のほう', translation: 'В этом направлении (небуквально)', kanji: 'の方' },
            { hiragana: 'ずっと', translation: 'Всё время', kanji: 'ずっと' },
            { hiragana: 'やっぱり', translation: 'Как ожидалось ', kanji: 'やっぱり' }
        ]
    },
    {
        title: 'Questions, places',
        words: [
            { hiragana: 'どんな', translation: 'Какие? Какого типа?' },
            { hiragana: 'どちら', translation: 'Который?' },
            { hiragana: 'どこの', translation: 'Откуда?' },
            { hiragana: 'どうして', translation: 'Почему? Как?' },
            { hiragana: 'だれの', translation: 'Чьё?' },
            { hiragana: 'どのくらい', translation: 'Как долго? Сколько?' },
            /*
            { hiragana: 'どっち', translation: 'Где?' },
            { hiragana: 'こっち', translation: 'Здесь' },
            { hiragana: 'そっち', translation: 'Там' }
            */
        ]
    },
    {
        title: 'Locations',
        words: [
            { hiragana: 'うえ', translation: 'Сверху, вверх, выше', kanji: '上' },
            { hiragana: 'した', translation: 'Снизу, под, ниже', kanji: '下' },
            { hiragana: 'なか', translation: 'Внутри', kanji: '中' },
            { hiragana: 'そと', translation: 'Снаружи', kanji: '外' },
            { hiragana: 'まえ', translation: 'Перед', kanji: '前' },
            { hiragana: 'うしろ', translation: 'Сзади', kanji: '後ろ' },
            { hiragana: 'となり', translation: 'Соседний', kanji: '隣' },
            { hiragana: 'ちかく', translation: 'Поблизости', kanji: '近く' },
            { hiragana: 'よこ', translation: 'Сторона', kanji: '横' },
            { hiragana: 'きた', translation: 'Север', kanji: '北' },
            { hiragana: 'みなみ', translation: 'Юг', kanji: '南' },
            { hiragana: 'にし', translation: 'Запад', kanji: '西' },
            { hiragana: 'ひがし', translation: 'Восток', kanji: '東' },
            { hiragana: 'いりぐち', translation: 'Вход', kanji: '入口' },
            { hiragana: 'でぐち', translation: 'Выход', kanji: '出口' }
        ]
    },
    {
        title: 'Spots around town',
        words: [
            { hiragana: 'がっこう', translation: 'Школа', kanji: '学校' },
            { hiragana: 'ぎんこう', translation: 'Банк', kanji: '銀行' },
            { hiragana: 'くうこう', translation: 'Аэропорт', kanji: '空港' },
            { hiragana: 'こうえん', translation: 'Парк', kanji: '公園' },
            { hiragana: 'スーパー', translation: 'Супермаркет' },
            { hiragana: 'だいがく', translation: 'Университет', kanji: '大学' },
            { hiragana: 'ちゅうしゃじょう', translation: 'Автостоянка', kanji: '駐車場' },
            { hiragana: 'ばすてい', translation: 'Автобусная астоновка' },
            { hiragana: 'びょういん', translation: 'Больница', kanji: '病院' },
            { hiragana: 'みち', translation: 'Дорога, улица', kanji: '道' },
            { hiragana: 'りょうりてん', translation: 'Ресторан', kanji: '料理店' }
        ]
    },
    {
        title: 'Technical',
        words: [
            { hiragana: 'かいしゃ', translation: 'Корпорация', kanji: '会社' },
            { hiragana: 'でんわ', translation: 'Телефон', kanji: '電話' },
            { hiragana: 'パソコン', translation: 'Персональный компьютер' },
            { hiragana: 'けいたいでんわ', translation: 'Мобильный телефон', kanji: '携帯電話' },
            { hiragana: 'ばんごう', translation: 'Номер', kanji: '番号' }
        ]
    },
    {
        title: 'Relations',
        words: [
            { hiragana: 'おとうさん', translation: 'Папа', kanji: 'お父さん' },
            { hiragana: 'おかあさん', translation: 'Мама', kanji: 'お母さん' },
            { hiragana: 'おにいさん', translation: 'Старший брат', kanji: '兄' },
            { hiragana: 'おねえさん', translation: 'Старшая сестра', kanji: 'お姉さん' },
            { hiragana: 'おとうとさん', translation: 'Младший брат', kanji: '弟さん' },
            { hiragana: 'いもうとさん', translation: 'Младшая сестра', kanji: '妹さん' },
            { hiragana: 'むすこさん', translation: 'Сын', kanji: '息子さん' },
            { hiragana: 'むすめさん', translation: 'Дочь', kanji: '娘さん' },
            { hiragana: 'まご', translation: 'Внук', kanji: '孫' },
            { hiragana: 'だんなさん', translation: 'Муж' },
            { hiragana: 'おくさん', translation: 'Жена', kanji: '奥さん' },
            { hiragana: 'つま', translation: 'Моя жена' },
            { hiragana: 'きょうだい', translation: 'Братья и сёстры', kanji: '兄弟' },
            { hiragana: 'そふ', translation: 'Дедушка', kanji: '祖父' },
            { hiragana: 'そぼ', translation: 'Бабушка', kanji: '祖母' },
            { hiragana: 'いとこ', translation: 'Двоюродный' }
        ]
    },
    {
        title: 'Present, Progressive, Past',
        words: [
            { hiragana: 'たべます', translation: 'To eat' }, // たべる
            { hiragana: 'たべません', translation: 'I don\'t eat' }, // たべない
            { hiragana: 'たべています', translation: 'I\'m eating' }, // たべている
            { hiragana: 'たべていません', translation: 'I\'m not eating' }, // たべていない
            { hiragana: 'たべました', translation: 'I ate' }, // たべた
            { hiragana: 'たべませんでした', translation: 'I didn\'t eat' } // たべなかった
        ]
    },
    {
        title: 'Pronouns',
        words: [
            { hiragana: 'かれの', translation: 'Его' },
            { hiragana: 'かのじょの', translation: 'Её' },
            { hiragana: 'わたしたちの', translation: 'Наше' },
            { hiragana: 'かれらの', translation: 'Их' },
            { hiragana: 'あなたたちの', translation: 'Ваше (мн. число)' },
            { hiragana: 'いっしょに', translation: 'Вместе' },
            { hiragana: 'じぶん', translation: 'myself, yourself, him(her)self', kanji: '自分' }
        ]
    },
    {
        title: 'Time',
        words: [
            { hiragana: 'ごぜん', translation: 'Время с 00:00 до 12:00 (a.m.)' },
            { hiragana: 'ごご', translation: 'Время с 12:00 до 24:00 (p.m.)' },
            { hiragana: 'つぎ', translation: 'Следующий' },
            { hiragana: 'はん', translation: 'Половина' },
            { hiragana: 'にじはん', translation: 'Половина третьего' },
            { hiragana: 'じゆうじかん', translation: 'Свободные часы' },
            { hiragana: 'から', translation: 'От' },
            { hiragana: 'まで', translation: 'До' },
            { hiragana: 'いつから', translation: 'С какого времени?' },
            { hiragana: 'いまから', translation: 'С этого момента' },
            { hiragana: 'いつでも', translation: 'В любое время' },
            { hiragana: 'よく', translation: 'Часто' },
            { hiragana: 'まいにち', translation: 'Каждый день' },
            { hiragana: 'さっき', translation: 'Недавно', kanji: 'さっき' },
            { hiragana: 'おひさしぶり', translation: 'Давно не виделись' },
            { hiragana: 'いつも', translation: 'Обычно, всегда' },
            { hiragana: 'とけい', translation: 'Часы' },
            { hiragana: 'とりあえず', translation: 'Для начала' },
            { hiragana: 'こんど', translation: 'В следующий раз, в другой раз', kanji: '今度' },
            { hiragana: 'もうすぐ', translation: 'Скоро', kanji: 'もう直ぐ' },
            { hiragana: 'かいえん', translation: 'Время начала выступления', kanji: '開演' }
        ]
    },
    {
        title: 'Minutes',
        words: [
            { hiragana: 'いっぷん', translation: '1 минута', kanji: '一分' },
            { hiragana: 'にふん', translation: '2 минуты', kanji: '二分' },
            { hiragana: 'さんぷん', translation: '3 минуты', kanji: '三分' },
            { hiragana: 'よんぷん', translation: '4 минуты', kanji: '四分' },
            { hiragana: 'ごふん', translation: '5 минут', kanji: '五分' },
            { hiragana: 'ろっぷん', translation: '6 минут', kanji: '六分' },
            { hiragana: 'ななふん', translation: '7 минут', kanji: '七分' },
            { hiragana: 'はちふん', translation: '8 минут', kanji: '八分' },
            { hiragana: 'きゅうふん', translation: '9 минут', kanji: '九分' },
            { hiragana: 'じゅっぷん', translation: '10 минут', kanji: '十分' },
            { hiragana: 'なんぷん', translation: 'Сколько минут?', kanji: '何分' }
        ]
    },
    {
        title: 'Dates',
        words: [
            { hiragana: 'たんじょうび', translation: 'День рождения', kanji: '誕生日' },
            { hiragana: 'あけまして', translation: 'С новым годом', kanji: '明けまして' },
            { hiragana: 'おめでとうございます', translation: 'Поздравляю' },
            { hiragana: 'がつ', translation: 'Месяц', kanji: '月' },
            { hiragana: 'にち', translation: 'День', kanji: '日' },

            { hiragana: 'いま', translation: 'Сейчас', kanji: '今' },
            { hiragana: 'やすみ', translation: 'Отпуск', kanji: '休み' },
            { hiragana: 'いつ', translation: 'Когда, время', kanji: '何時' },
            { hiragana: 'しゅうかん', translation: 'Неделя', kanji: '週間' },

            { hiragana: 'きのう', translation: 'Вчера', kanji: '昨日' },
            { hiragana: 'きょう', translation: 'Сегодня', kanji: '今日 ' },
            { hiragana: 'あした', translation: 'Завтра', kanji: '明日' },
            { hiragana: 'あさって', translation: 'Послезавтра', kanji: '明後日' },

            { hiragana: 'せんしゅう', translation: 'Прошлая неделя', kanji: '先週' },
            { hiragana: 'こんしゅう', translation: 'Текущая неделя', kanji: '今週' },
            { hiragana: 'らいしゅう', translation: 'Следующая неделя', kanji: '来週' },

            { hiragana: 'せんげつ', translation: 'Прошлый месяц', kanji: '先月' },
            { hiragana: 'こんげつ', translation: 'Текущий месяц', kanji: '今月' },
            { hiragana: 'らいげつ', translation: 'Следующий месяц', kanji: '来月' },

            { hiragana: 'きょねん', translation: 'В прошлом году', kanji: '去年' },
            { hiragana: 'ことし', translation: 'В этом году', kanji: '今年' },
            { hiragana: 'らいねん', translation: 'В следующем году', kanji: '来年' },

            { hiragana: 'そのあと', translation: 'После этого', kanji: 'その後' },
            { hiragana: 'あさ', translation: 'Утро', kanji: '朝' },
            { hiragana: 'ひる', translation: 'День', kanji: '昼' },
            { hiragana: 'ばん', translation: 'Вечер', kanji: '晩' },
            { hiragana: 'よる', translation: 'Ночь', kanji: '夜' }
        ]
    },
    {
        title: 'Week Days',
        words: [
            { hiragana: 'げつようび', translation: 'Понедельник', kanji: '月曜日' },
            { hiragana: 'かようび', translation: 'Вторник', kanji: '火曜日' },
            { hiragana: 'すいようび', translation: 'Среда', kanji: '水曜日' },
            { hiragana: 'もくようび', translation: 'Четверг', kanji: '木曜日' },
            { hiragana: 'きんようび', translation: 'Пятница', kanji: '金曜日' },
            { hiragana: 'どようび', translation: 'Суббота', kanji: '土曜日' },
            { hiragana: 'にちようび', translation: 'Воскресенье', kanji: '日曜日' },
            { hiragana: 'なんようび', translation: 'Какой день недели?', kanji: '何曜日' },
            { hiragana: 'へいじつ', translation: 'Будние дни', kanji: '平日' }
        ]
    },
    {
        title: 'Month Dates',
        words: [
            { hiragana: 'ついたち', translation: '1 число', kanji: '一日' },
            { hiragana: 'ふつか', translation: '2 число', kanji: '二日' },
            { hiragana: 'みっか', translation: '3 число', kanji: '三日' },
            { hiragana: 'よっか', translation: '4 число', kanji: '四日' },
            { hiragana: 'いつか', translation: '5 число', kanji: '五日' },
            { hiragana: 'むいか', translation: '6 число', kanji: '六日' },
            { hiragana: 'なのか', translation: '7 число', kanji: '七日' },
            { hiragana: 'ようか', translation: '8 число', kanji: '八日' },
            { hiragana: 'ここのか', translation: '9 число', kanji: '九日' },
            { hiragana: 'とおか', translation: '10 число', kanji: '十日' },
            /*
            { hiragana: 'じゅういちにち', translation: '11 число' },
            { hiragana: 'じゅうににち', translation: '12 число' },
            { hiragana: 'じゅうさんにち', translation: '13 число' },
            { hiragana: 'じゅうよっか', translation: '14 число' },
            { hiragana: 'じゅうごにち', translation: '15 число' },
            { hiragana: 'じゅうろくにち', translation: '16 число' },
            { hiragana: 'じゅうななにち', translation: '17 число' },
            { hiragana: 'じゅうはちにち', translation: '18 число' },
            { hiragana: 'じゅうくにち', translation: '19 число' },
            */
            { hiragana: 'はつか', translation: '20 число', kanji: '二十日' },
            /*
            { hiragana: 'にじゅういちにち', translation: '21 число' },
            { hiragana: 'にじゅうににち', translation: '22 число' },
            { hiragana: 'にじゅうさんにち', translation: '23 число' },
            { hiragana: 'にじゅうよんにち', translation: '24 число' },
            { hiragana: 'にじゅうごにち', translation: '25 число' },
            { hiragana: 'にじゅうろくにち', translation: '26 число' },
            { hiragana: 'にじゅうななにち', translation: '27 число' },
            { hiragana: 'にじゅうはちにち', translation: '28 число' },
            { hiragana: 'にじゅうくにち', translation: '29 число' },
            { hiragana: 'さんじゅうにち', translation: '30 число' },
            { hiragana: 'さんじゅういちにち', translation: '31 число' }
            */
        ]
    },
    {
        title: 'Counters. General',
        words: [
            { hiragana: 'ひとつ', translation: 'Один', kanji: '一つ' },
            { hiragana: 'ふたつ', translation: 'Два', kanji: '二つ' },
            { hiragana: 'みっつ', translation: 'Три', kanji: '三つ' },
            { hiragana: 'よっつ', translation: 'Четыре', kanji: '四つ' },
            { hiragana: 'いつつ', translation: 'Пять', kanji: '五つ' },
            { hiragana: 'むっつ', translation: 'Шесть', kanji: '六つ' },
            { hiragana: 'ななつ', translation: 'Семь', kanji: '七つ' },
            { hiragana: 'やっつ', translation: 'Восемь', kanji: '八つ' },
            { hiragana: 'ここのつ', translation: 'Девять', kanji: '九つ' },
            { hiragana: 'とお', translation: 'Десять', kanji: '十つ' },
            { hiragana: 'いくつ', translation: 'Сколько?', kanji: '幾つ' }
        ]
    },
    {
        title: 'Counters. Floors',
        words: [
            { hiragana: 'いっかい', translation: '1 этаж', kanji: '一階' },
            { hiragana: 'にかい', translation: '2 этаж', kanji: '二階' },
            { hiragana: 'さんかい、さんがい', translation: '3 этаж', kanji: '三階' },
            { hiragana: 'よんかい', translation: '4 этаж', kanji: '四階' },
            { hiragana: 'ごかい', translation: '5 этаж', kanji: '五階' },
            { hiragana: 'ろっかい', translation: '6 этаж', kanji: '六階' },
            { hiragana: 'ななかい', translation: '7 этаж', kanji: '七階' },
            { hiragana: 'はっかい', translation: '8 этаж', kanji: '八階' },
            { hiragana: 'きゅうかい', translation: '9 этаж', kanji: '九階' },
            { hiragana: 'じゅうかい', translation: '10 этаж', kanji: '十階' },
            { hiragana: 'じゅういっかい', translation: '11 этаж', kanji: '十一階' },
            { hiragana: 'じゅうにかい', translation: '12 этаж', kanji: '十二階' },
            { hiragana: 'なんかい、なんがい', translation: 'Какой этаж?', kanji: '何階' }
        ]
    },
    {
        title: 'Counters. People',
        words: [
            { hiragana: 'ひとり', translation: 'Один человек', kanji: '一人' },
            { hiragana: 'ふたり', translation: 'Два человека', kanji: '二人' },
            { hiragana: 'さんにん', translation: 'Три человека', kanji: '三人' },
            { hiragana: 'なんにん', translation: 'Сколько человек?', kanji: '何人' }
        ]
    },
    {
        title: 'Age Numbers',
        words: [
            { hiragana: 'いっさい', translation: '1 год', kanji: '一歳' },
            { hiragana: 'にさい', translation: '2 года', kanji: '二歳' },
            { hiragana: 'さんさい', translation: '3 года', kanji: '三歳' },
            { hiragana: 'よんさい', translation: '4 года', kanji: '四歳' },
            { hiragana: 'ごさい', translation: '5 лет', kanji: '五歳' },
            { hiragana: 'ろくさい', translation: '6 лет', kanji: '六歳' },
            { hiragana: 'ななさい', translation: '7 лет', kanji: '七歳' },
            { hiragana: 'はっさい', translation: '8 лет', kanji: '八歳' },
            { hiragana: 'きゅうさい', translation: '9 лет', kanji: '九歳' },
            { hiragana: 'じゅっさい', translation: '10 лет', kanji: '十歳' },
            { hiragana: 'じゅいっさい', translation: '11 лет', kanji: '十一歳' },
            { hiragana: 'はたち', translation: '20 лет', kanji: '二十歳' },
            { hiragana: 'にじゅうっさい', translation: '21 год', kanji: '二十一歳' }
        ]
    },
    {
        title: 'Roles',
        words: [
            { hiragana: 'けいさつかん', translation: 'Офицер полиции', kanji: '警察官' },
            { hiragana: 'りゅうがくせい', translation: 'Студент по обмену', kanji: '留学生' },
            { hiragana: 'がくせい', translation: 'Студент', kanji: '学生' },
            { hiragana: 'せんこう', translation: 'Специальность', kanji: '専攻' },
            { hiragana: 'つうこうにん', translation: 'Прохожий', kanji: '通行人' }
        ]
    },
    {
        title: 'Body parts',
        words: [
            { hiragana: 'あたま', translation: 'Голова', kanji: '頭' },
            { hiragana: 'かみ', translation: 'Волосы, причёска' },
            { hiragana: 'こえ', translation: 'Голос', kanji: '声' },
            { hiragana: 'き', translation: 'Чувство', kanji: '気' },
            { hiragana: 'かお', translation: 'Лицо', kanji: '顔' },
            { hiragana: 'うで', translation: 'Рука (arm)', kanji: '腕' },
            { hiragana: 'て', translation: 'Кисть руки (hand)', kanji: '手' },
            { hiragana: 'あし', translation: 'Нога', kanji: '足' },
            { hiragana: 'はな', translation: 'Нос', kanji: '鼻' },
            { hiragana: 'くち', translation: 'Рот', kanji: '口' },
            { hiragana: 'くちびる', translation: 'Губы', kanji: '唇' },
            { hiragana: 'は', translation: 'Зуб', kanji: '歯' },
            { hiragana: 'のど', translation: 'Горло', kanji: 'のど' },
            { hiragana: 'くび', translation: 'Шея', kanji: '首' },
            { hiragana: 'かた', translation: 'Плечо', kanji: '肩' },
            { hiragana: 'せなか', translation: 'Спина', kanji: '背中' },
            { hiragana: 'おなか', translation: 'Живот', kanji: 'お腹' },
            { hiragana: 'むね', translation: 'Грудь', kanji: '胸' },
            { hiragana: 'ひざ', translation: 'Колено', kanji: '膝' },
            { hiragana: 'ゆび', translation: 'Палец', kanji: '指' },
            { hiragana: 'からだ', translation: 'Тело', kanji: '体' },
            { hiragana: 'せ', translation: 'Рост', kanji: '背' },
            { hiragana: 'みみ', translation: 'Ухо', kanji: '耳' }
        ]
    },
    /*
    {
        title: 'Numbers Tens of Thousands',
        words: [
            { hiragana: 'いちまん', translation: '10 000', kanji: '一万' },
            { hiragana: 'にまん', translation: '20 000', , kanji: 'ニ万' },
            { hiragana: 'さんまん', translation: '30 000', kanji: '三万' },
            { hiragana: 'よんまん', translation: '40 000', kanji: '四万' },
            { hiragana: 'ごまん', translation: '50 000', kanji: '五万' },
            { hiragana: 'ろくまん', translation: '60 000', kanji: '六万' },
            { hiragana: 'ななまん', translation: '70 000', kanji: '七万' },
            { hiragana: 'はちまん', translation: '80 000', kanji: '八万' },
            { hiragana: 'きゅうまん', translation: '90 000', kanji: '九万' }
        ]
    },
    */
    {
        title: 'Combinations',
        words: [
            { hiragana: 'それとも', translation: 'Или' },
            { hiragana: 'それから', translation: 'И, и также' }
        ]
    },
    {
        title: 'Phrases',
        words: [
            { hiragana: 'いらっしゃいませ', translation: 'Как я могу вам помочь?' },
            { hiragana: 'おじゃまします', translation: 'Жаль беспокоить вас (когда входишь или покидаешь чужой дом)' },
            { hiragana: 'どういたしまして', translation: 'Пожалуйста, не за что (после благодарности)' },
            { hiragana: 'おまたせしました', translation: 'Простите, что заставили ждать' },
            { hiragana: 'こちそうさまでした', translation: 'Спасибо за еду' },
            { hiragana: 'ただいま', translation: 'Я дома' },
            { hiragana: 'おかえりなさい', translation: 'С возвращением' },
            { hiragana: 'かんけいない', translation: 'Не имеет значения' },
            { hiragana: 'おつかれさま', translation: 'Спасибо, достаточно на сегодня, привет (на работе)' },
            { hiragana: 'これでいい', translation: 'Это хорошо' },
            { hiragana: 'どうしましたか', translation: 'Что случилось?' },
            { hiragana: 'かしこまりました', translation: 'Да, сэр' },
            { hiragana: 'おあがりください', translation: 'Пожалуйста, поднимайтесь' },
            { hiragana: 'おはいりください', translation: 'Пожалуйста, проходите' },
            { hiragana: 'おかげさまで', translation: 'Благодарен вам' },
            { hiragana: 'いかが, どう', translation: 'Как насчёт?' },
            { hiragana: 'こちらこそ', translation: 'То же самое и я' },
            { hiragana: 'けっこう', translation: 'Нет, спасибо', kanji: '結構' },
            { hiragana: 'おせわになりました', translation: 'Спасибо за вашу доброту', kanji: 'お世話になりました' }
        ]
    },
    {
        title: 'Medicine',
        words: [
            { hiragana: 'くすり', translation: 'Медицина', kanji: '薬' },
            { hiragana: 'かぜ', translation: 'Простуда', kanji: '風邪' },
            { hiragana: 'しんさつ', translation: 'Медицинская консультация', kanji: '診察' },
            { hiragana: 'はきけ', translation: 'Тошнота', kanji: '吐き気' },
            { hiragana: 'ねつ', translation: 'Зной, температура', kanji: '熱' },
            { hiragana: 'ど', translation: 'Степень, температура', kanji: '度' },
            { hiragana: 'かんごし', translation: 'Медсестра, медбрат', kanji: '看護師' },
            { hiragana: 'やっきょく', translation: 'Аптека', kanji: '薬局' }
        ]
    },
    {
        title: 'Money',
        words: [
            { hiragana: 'ぜい', translation: 'Налог', kanji: '税' },
            { hiragana: 'ぜいこみ', translation: 'Налог включён', kanji: '税込み' },
            { hiragana: 'おかね', translation: 'Деньги', kanji: 'お金' },
            { hiragana: 'げんきん', translation: 'Наличные', kanji: '現金' },
            { hiragana: 'かかく', translation: 'Цена', kanji: '価格' },
            { hiragana: 'かいけい', translation: 'Счёт, чек', kanji: '会計' },
            { hiragana: 'たま', translation: 'Монета, мячик', kanji: '玉' },
            { hiragana: 'さつ', translation: 'Банкнота', kanji: '札' },
            { hiragana: 'りょうしゅうしょ', translation: 'Квитанция', kanji: '領収書' },
            { hiragana: 'おつり', translation: 'Сдача', kanji: 'おつり' },
            { hiragana: 'しょほうせん', translation: 'Рецепт', kanji: '処方箋' }
        ]
    },
    {
        title: 'Food',
        words: [
            { hiragana: 'もちかえり', translation: 'Взять с собой' },
            { hiragana: 'てんない', translation: 'В магазине' },
            { hiragana: 'おにぎり', translation: 'Рисовый шарик', kanji: 'お握り' },
            { hiragana: 'ひるごはん', translation: 'Обед', kanji: '昼ご飯' },
            { hiragana: 'おかし', translation: 'Конфета', kanji: 'お菓子' },
            { hiragana: 'やさい', translation: 'Овощи', kanji: '野菜' },
            { hiragana: 'さしみ', translation: 'Порезанная рыба', kanji: '刺身' },
            { hiragana: 'しお', translation: 'Соль', kanji: '塩' },
            { hiragana: 'さら', translation: 'Тарелка', kanji: '皿' },
            { hiragana: 'からあげ', translation: 'Жареная курица' },
            { hiragana: 'かつどん', translation: 'Жареная свинина в панировке и рис', kanji: 'カツ丼' },
            { hiragana: 'とんかつ', translation: 'Свиная котлета', kanji: '豚カツ' },
            { hiragana: 'ていしょく', translation: 'Комплексное блюдо дня', kanji: '定食' },
            { hiragana: 'おおもり', translation: 'Большая порция', kanji: '大盛り' },
            { hiragana: 'しょうゆ', translation: 'Соевый соус', kanji: 'しょうゆ' },
            { hiragana: 'あさめしまえ', translation: 'Кусок торта', kanji: '朝飯前' }
        ]
    },
    {
        title: 'Class 1 verbs. When ます is preceded by -i',
        words: [
            { hiragana: 'あいます', translation: 'あう' },
            { hiragana: 'いきます', translation: 'いく' },
            { hiragana: 'はなします', translation: 'はなす' },
            { hiragana: 'のみます', translation: 'のむ' },
            { hiragana: 'まちます', translation: 'まつ' },
            { hiragana: 'あります', translation: 'ある' }
        ]
    },
    {
        title: 'Class 2 verbs. When ます is preceded by -e or a one syllable sound',
        words: [
            { hiragana: 'たべます', translation: 'たべる' },
            { hiragana: 'みます', translation: 'みる' },
            { hiragana: 'ねます', translation: 'ねる' }
        ]
    },
    {
        title: 'Class 3 verbs.',
        words: [
            { hiragana: 'します', translation: 'する' },
            { hiragana: 'きます', translation: 'くる' }
        ]
    }
];
