module.exports = [
    {
        title: 'Verbs',
        words: [
            { kana: 'はいります', translation: 'Войти, зайти в', kanji: '入ります' },
            { kana: 'つかいます', translation: 'Использовать', kanji: '使います' },
            { kana: 'とります', translation: 'Фотографировать', kanji: '撮ります' },
            { kana: 'のります', translation: 'Зайти в поезд, автобус', kanji: '乗ります' },
            { kana: 'きんちょうします', translation: 'Нервничать', kanji: '緊張します' },
            { kana: 'わすれます', translation: 'Забывать', kanji: '忘れます' },
            { kana: 'しんぱいします', translation: 'Беспокоиться', kanji: '心配します' },
            { kana: 'もうします', translation: 'Называйте меня', kanji: '申します' },
            { kana: 'よみます', translation: 'Читать', kanji: '読みます' },
            { kana: 'かいます', translation: 'Покупать', kanji: '買います' },
            { kana: 'はらいます', translation: 'Платить', kanji: '払います' },
            { kana: 'かきます', translation: 'Писать', kanji: '掻きます' },
            { kana: 'つけます', translation: 'Включить', kanji: '就けます' },
            { kana: 'けします', translation: 'Выключать', kanji: '消します' },
            { kana: 'まがります', translation: 'Поворачивать', kanji: '曲がります' },
            { kana: 'もらいます', translation: 'Принимать', kanji: '貰います' },
            { kana: 'おくります', translation: 'Отправлять', kanji: '送ります' },
            { kana: 'おします', translation: 'Толкать', kanji: '押します' },
            { kana: 'すいます', translation: 'Курить', kanji: '吸います' },
            { kana: 'つくります', translation: 'Производить, делать', kanji: '作ります' },
            { kana: 'うります', translation: 'Продавать', kanji: '売ります' },
            { kana: 'あげます', translation: 'Давать' },
            { kana: 'あけます', translation: 'Открывать', kanji: '空きます' },
            { kana: 'みせます', translation: 'Показывать', kanji: '見せます' },
            { kana: 'おります', translation: 'Выходить (из поезда)', kanji: '降ります' },
            { kana: 'おしえます', translation: 'Учить', kanji: '教えます' },
            { kana: 'しめます', translation: 'Закрывать', kanji: '閉めます' },
            { kana: 'とまります', translation: 'Остановиться, припарковаться', kanji: '止まります' },
            { kana: 'べんきょうします', translation: 'Учиться', kanji: '勉強します' },
            { kana: 'かえります', translation: 'Возвращаться', kanji: '帰りむす' },
            { kana: 'ささえます', translation: 'Поддерживать', kanji: '支えます' },
            { kana: 'おなかがすきます', translation: 'Быть голодным', kanji: 'お腹が空きます' },
            { kana: 'ぬぎます', translation: 'Раздеваться', kanji: '脱ぎます' },
            { kana: 'きかざります', translation: 'Одеваться', kanji: '着飾ります' },
            { kana: 'なります', translation: 'Становиться', kanji: '成ります' },
            { kana: 'ねます', translation: 'Ложиться спать' },
            { kana: 'まぜます', translation: 'Смешать', kanji: '交ぜます' },
            { kana: 'あるきます', translation: 'Ходить', kanji: '歩きます' },
            { kana: 'とびます', translation: 'Лететь', kanji: '飛びます' },
            { kana: 'わたります', translation: 'Пересекать', kanji: '渡ります' },
            { kana: 'だきしめます', translation: 'Обнимать', kanji: '抱きしめます' },
            { kana: 'しゅっぱつします', translation: 'Уходить', kanji: '出発します' },
            { kana: 'とうちゃくします', translation: 'Приезжать', kanji: '到着します' },
            { kana: 'つかれます', translation: 'Уставать', kanji: '疲れます' },
            { kana: 'えらびます', translation: 'Выбирать', kanji: '選びます' },
            { kana: 'きめます', translation: 'Решить (decide)', kanji: '決めます' },
            { kana: 'とまります', translation: 'Оставаться в', kanji: '泊まります' },
            { kana: 'およぎます', translation: 'Плавать', kanji: '泳ぎます' },
            { kana: 'のぼります', translation: 'Подниматься, забираться', kanji: '上ります' },
            { kana: 'たてます', translation: 'Строить', kanji: '建てます' },
            { kana: 'そそぎます', translation: 'Наполнить (водой)', kanji: '注ぎます' },
            { kana: 'あそびます', translation: 'Играть', kanji: '遊びます' },
            { kana: 'ぬります', translation: 'Рисовать', kanji: '塗ります' },
            { kana: 'さけびます', translation: 'Кричать', kanji: '叫びます' },
            { kana: 'かけます', translation: 'Звонить', kanji: '掛けます' },
            { kana: 'すみます', translation: 'Жить', kanji: '住みます' },
            { kana: 'おきます', translation: 'Просыпаться', kanji: '起きます' },
            { kana: 'おきます', translation: 'Положить', kanji: '置きます' },
            { kana: 'きります', translation: 'Резать', kanji: '切ります' },
            { kana: 'さきます', translation: 'Расцвести', kanji: '咲きます' },
            { kana: 'しょうたいします', translation: 'Пригласить', kanji: '招待します' },
            { kana: 'つかまえます', translation: 'Поймать', kanji: '捕まえます' },
            { kana: 'みつけます', translation: 'Найти', kanji: '見つけます' },
            { kana: 'おとします', translation: 'Уронить, падать', kanji: '落とします' },
            { kana: 'こたえます', translation: 'Отвечать', kanji: '答えます' },
            { kana: 'さわります', translation: 'Трогать', kanji: '触ります' },
            { kana: 'なくします', translation: 'Потерять', kanji: '無くします' },
            { kana: 'しにます', translation: 'Умереть', kanji: '死にます' },
            { kana: 'きえます', translation: 'Исчезнуть', kanji: '消えます' },
            { kana: 'うちます', translation: 'Бить, ударить', kanji: '打ちます' },
            { kana: 'まけます', translation: 'Проиграть', kanji: '負けます' },
            { kana: 'こわれます', translation: 'Сломать', kanji: '壊れます' },
            { kana: 'やきます', translation: 'Печь', kanji: '焼きます' },
            { kana: 'さがします', translation: 'Искать', kanji: '探します' },
            { kana: 'かわります', translation: 'Менять', kanji: '変わります' },
            { kana: 'いのります', translation: 'Молиться, желать', kanji: '祈ります' },
            { kana: 'ちかいます', translation: 'Клясться', kanji: '誓います' },
            { kana: 'とどきます', translation: 'Достичь', kanji: '届きます' },
            { kana: 'おどろきます', translation: 'Удивлять', kanji: '驚きます' },
            { kana: 'あたためます', translation: 'Согреть', kanji: '温めます' },
            { kana: 'おくれます', translation: 'Опоздать, задержаться', kanji: '遅れます' },
            { kana: 'ふざけます', translation: 'Шутить, насмехаться', kanji: '巫山戯ます' },
            { kana: 'かんがえます', translation: 'Думать', kanji: '考えます' },
            { kana: 'かぞえます', translation: 'Считать', kanji: '数えます' },
            { kana: 'そうじします', translation: 'Чистить', kanji: '掃除します' },
            { kana: 'ふきます', translation: 'Протирать', kanji: '拭きます' },
            { kana: 'うたいます', translation: 'Петь', kanji: '歌います' },
            { kana: 'なきます', translation: 'Плакать', kanji: '泣きます' },
            { kana: 'わらいます', translation: 'Смеяться', kanji: '笑います' },
            { kana: 'うまれます', translation: 'Родиться', kanji: '生まれます' },
            { kana: 'かかります', translation: 'Стоить, занять', kanji: '掛かります' },
            { kana: 'おぼえます', translation: 'Запомнить', kanji: '覚えます' },
            { kana: 'おぼれます', translation: 'Утонуть', kanji: '溺れます' },
            { kana: 'おごります', translation: 'Угощать', kanji: '奢ります' },
            { kana: 'ながれます', translation: 'Течь', kanji: '流れます' },
            { kana: 'にあいます', translation: 'Подходить (одежда и пр.)', kanji: '似合います' },
            { kana: 'わります', translation: 'Разделять', kanji: '割ります' },
            { kana: 'かぶります', translation: 'Одевать, носить', kanji: '被ぶります' },
            { kana: 'ふとります', translation: 'Толстеть', kanji: '太ります' },
            { kana: 'おうえんします', translation: 'Поддерживать (болеть)', kanji: '応援します' },
            { kana: 'おもいます', translation: 'Считать, предполагать', kanji: '思います' },
            { kana: 'よびます', translation: 'Позвонить', kanji: '呼びます' },
            { kana: 'すごします', translation: 'Провести время', kanji: '過ごします' },
            { kana: 'つきます', translation: 'Прибывать (домой)', kanji: '着きます' },
            { kana: 'ばれます', translation: 'Быть разоблачённым (секрет)' },
            { kana: 'ばらします', translation: 'Разоблачить (секрет)' },
            { kana: 'まもります', translation: 'Защищать', kanji: '守ります' },
            { kana: 'とります', translation: 'Собирать', kanji: '採ります' },
            { kana: 'まにあいます', translation: 'Успеть вовремя', kanji: '間に合います' },
            { kana: 'かまいます', translation: 'Заботиться о, беспокоиться о', kanji: '構います' },
            { kana: 'かよいます', translation: 'Посещать регулярно (школу, работу)', kanji: '通います' },
            { kana: 'きにいります', translation: 'Нравиться', kanji: '気に⼊ります' },
            { kana: 'こえます', translation: 'Пересечь, пройти через', kanji: '越えます' },
            { kana: 'りかいできます', translation: 'Быть способным понять', kanji: '理解出来ます' },
            { kana: 'りかいできません', translation: 'Быть неспособным понять', kanji: '理解できません' },
            { kana: 'はしります', translation: 'Бежать', kanji: '走ります' },
            { kana: 'おこります', translation: 'Злиться', kanji: '怒ります' },
            { kana: 'なげます', translation: 'Бросить', kanji: '投げます' },
            { kana: 'おわります', translation: 'Закончить', kanji: '終わります' },
            { kana: 'ためします', translation: 'Тестировать', kanji: '試します' },
            { kana: 'ハイハイする', translation: 'Ползать' },
            { kana: 'ふります', translation: 'Падать (осадки)', kanji: '降ります' },
            { kana: 'おちます', translation: 'Падать', kanji: '落ちます' },
            { kana: 'たずねます', translation: 'Посещать', kanji: '訪ねます' },
            { kana: 'ひろいます', translation: 'Подобрать (буквально или кого-то на машине)', kanji: '拾います' }
        ]
    },
    {
        title: 'Verbs 出す',
        description: 'Окончание 出す означает начать делать что-то',
        words: [
            { kana: 'わらいだす', translation: 'Засмеяться, начать смеяться', kanji: '笑い出す' },
            { kana: 'おこりだす', translation: 'Разразиться гневом', kanji: '怒り出す' },
            { kana: 'もれだす', translation: 'Вызвать утечку', kanji: '漏れ出す' },
            { kana: 'なげだす', translation: 'Выкинуть', kanji: '投げ出す' },
            { kana: 'はしりだす', translation: 'Начать бежать, побежать', kanji: '走り出す' }
        ]
    },
    {
        title: 'Verbs 超える',
        description: 'Окончание 超えます означает сделать что-то над, через',
        words: [
            { kana: 'のりこえます', translation: 'Проехать, переехать', kanji: '乗り越えます' },
            { kana: 'とびこえます', translation: 'Перепрыгнуть', kanji: '飛び越えます' }
        ]
    },
    {
        title: 'Verbs 込む',
        description: 'Окончание 込む означает действие + внутрь чего-то',
        words: [
            { kana: 'かきこむ', translation: 'Заполнить', kanji: '書き込む' },
            { kana: 'はいりこむ', translation: 'Зайти в', kanji: '入り込む' },
            { kana: 'のみこむ ', translation: 'Проглотить', kanji: '飲み込む' },
            { kana: 'とけこむ', translation: 'Таять в', kanji: '溶け込む' },
            { kana: 'とびこむ', translation: 'Запрыгнуть в', kanji: '飛び込む' }
        ]
    },
    {
        title: 'Nouns',
        words: [
            { kana: 'めんきょ', translation: 'Лицензия, уроки', kanji: '免許' },
            { kana: 'うんてん', translation: 'Вождение', kanji: '運転' },
            { kana: 'うんてんしゅ', translation: 'Водитель', kanji: '運転手' },
            { kana: 'しゃしん', translation: 'Фото', kanji: '写真' },
            { kana: 'おきゃくさん', translation: 'Посетитель, гость', kanji: 'お客さん' },
            { kana: 'てんいん', translation: 'Работник, клерк', kanji: '店員' },
            { kana: 'りょこう', translation: 'Поездка, путешествие', kanji: '旅行' },
            { kana: 'たいざい', translation: 'Пребывание', kanji: '滞在' },
            { kana: 'もくてき', translation: 'Цель', kanji: '目的' },
            { kana: 'きかん', translation: 'Продолжительность', kanji: '期間' },
            { kana: 'たいざいきかん', translation: 'Продолжительность пребывания' },
            { kana: 'たいざいもくてき', translation: 'Цель пребывания' },
            { kana: 'かんこう', translation: 'Осмотр достопримечательностей', kanji: '観光' },
            { kana: 'よてい', translation: 'План', kanji: '予定' },
            { kana: 'うち', translation: 'Дом, моя семья, моя', kanji: '家' },
            { kana: 'うそつき', translation: 'Лжец', kanji: '嘘つき' },
            { kana: 'おさけ', translation: 'Алкоголь', kanji: 'お酒' },
            { kana: 'りょうり', translation: 'Еда', kanji: '料理' },
            { kana: 'まくら', translation: 'Подушка', kanji: '枕' },
            { kana: 'かばん', translation: 'Сумка', kanji: '鞄' },
            { kana: 'ぼうし', translation: 'Шляпа', kanji: '帽子' },
            { kana: 'うそ', translation: 'Ложь', kanji: '嘘' },
            { kana: 'しんぶん', translation: 'Газета', kanji: '新聞' },
            { kana: 'どうぶつえん', translation: 'Зоопарк', kanji: '動物園' },
            { kana: 'どうぶつ', translation: 'Животное', kanji: '動物' },
            { kana: 'おんがく', translation: 'Музыка', kanji: '音楽' },
            { kana: 'へや', translation: 'Комната', kanji: '部屋' },
            { kana: 'いす', translation: 'Стул', kanji: '椅子' },
            { kana: 'ひこうき', translation: 'Самолёт, рейс', kanji: '飛行機' },
            { kana: 'おみやげ', translation: 'Сувенир', kanji: 'お土産' },
            { kana: 'おと', translation: 'Звук', kanji: '音' },
            { kana: 'しゃこ', translation: 'Гараж', kanji: '車庫' },
            { kana: 'ちかてつ', translation: 'Метро', kanji: '地下鉄' },
            { kana: 'さいしゅう', translation: 'Последний', kanji: '最終' },
            { kana: 'しゅうでん', translation: 'Последний поезд', kanji: '終電' },
            { kana: 'ふくしゅう', translation: 'Месть', kanji: '復讐' },
            { kana: 'まちがい', translation: 'Ошибка', kanji: '間違い' },
            { kana: 'ぐうぜん', translation: 'Совпадение', kanji: '偶然' },
            { kana: 'きず', translation: 'Царапина', kanji: '傷' },
            { kana: 'ようじ', translation: 'Задачи', kanji: '用事' },
            { kana: 'ざっし', translation: 'Журнал', kanji: '雑誌' },
            { kana: 'おみせ', translation: 'Магазин', kanji: 'お店' },
            { kana: 'ちゅうもん', translation: 'Заказ', kanji: '注文' },
            { kana: 'しゅっぱつ', translation: 'Выезд', kanji: '出発' },
            { kana: 'とうちゃく', translation: 'Приезд', kanji: '到着' },
            { kana: 'にもつ', translation: 'Багаж', kanji: '荷物' },
            { kana: 'ちず', translation: 'Карта', kanji: '地図' },
            { kana: 'てら', translation: 'Храм', kanji: '寺' },
            { kana: 'ところ', translation: 'Место', kanji: '所' },
            { kana: 'きょうみ', translation: 'Интерес', kanji: '興味' },
            { kana: 'におい', translation: 'Запах', kanji: '匂い' },
            { kana: 'あじ', translation: 'Вкус', kanji: '味' },
            { kana: 'しあわせ', translation: 'Счастье', kanji: '幸せ' },
            { kana: 'つくえ', translation: 'Парта', kanji: '机' },
            { kana: 'いろ', translation: 'Цвет', kanji: '色' },
            { kana: 'てがみ', translation: 'Письмо', kanji: '手紙' },
            { kana: 'かんがえ', translation: 'Мысль, идея', kanji: '考え' },
            { kana: 'ゆかた', translation: 'Кимоно', kanji: '浴衣' },
            { kana: 'かしゅ', translation: 'Певец', kanji: '歌手' },
            { kana: 'おまつり', translation: 'Фестиваль', kanji: 'お祭り' },
            { kana: 'じんせい', translation: 'Жизнь', kanji: '人生' },
            { kana: 'みずうみ', translation: 'Озеро', kanji: '湖' },
            { kana: 'ゆめ', translation: 'Сон', kanji: '夢' },
            { kana: 'じゅうしょ', translation: 'Адрес', kanji: '住所' },
            { kana: 'おかわり', translation: 'Добавка', kanji: 'お代わり' },
            { kana: 'かいだん', translation: 'Ступеньки', kanji: '階段' },
            { kana: 'きぼう', translation: 'Надежда', kanji: '希望' },
            { kana: 'れつ', translation: 'Очередь', kanji: '列' },
            { kana: 'さいこう', translation: 'Лучший', kanji: '最高' },
            { kana: 'さいぜん', translation: 'Лучший', kanji: '最善' },
            { kana: 'さいてい', translation: 'Худший', kanji: '最低' },
            { kana: 'さいあく', translation: 'Худший', kanji: '最悪' },
            { kana: 'うわさ', translation: 'Слухи', kanji: '噂' },
            { kana: 'こじん', translation: 'Личный', kanji: '個人' },
            { kana: 'たな', translation: 'Полка', kanji: '棚' },
            { kana: 'かいもの', translation: 'Покупки', kanji: '買い物' },
            { kana: 'しあい', translation: 'Матч, игра', kanji: '試合' },
            { kana: 'しつもん', translation: 'Вопросы', kanji: '質問' },
            { kana: 'あかちゃん', translation: 'Грудничковый ребёнок', kanji: '赤ちゃん' },
            { kana: 'おいわい', translation: 'Поздравление', kanji: 'お祝い' },
            { kana: 'みらい', translation: 'Будущее', kanji: '未来' },
            { kana: 'しょうらい', translation: 'Будущее', kanji: '将来' },
            { kana: 'じょうだん', translation: 'Шутка', kanji: '冗談' },
            { kana: 'はんぶん', translation: 'Половина', kanji: '半分' },
            { kana: 'にんき', translation: 'Популярность', kanji: '人気' },
            { kana: 'しんこう', translation: 'Вера, доверие', kanji: '信仰' },
            { kana: 'ないしょ', translation: 'Секрет, тайна', kanji: '内緒' },
            { kana: 'ひみつ', translation: 'Секрет', kanji: '秘密' },
            { kana: 'しゅみ', translation: 'Хобби', kanji: '趣味' },
            { kana: 'かぎ', translation: 'Ключ', kanji: '鍵' },
            { kana: 'おふろ', translation: 'Ванна', kanji: 'お風呂' },
            { kana: 'でんき', translation: 'Электричество, свет', kanji: '電気' },
            { kana: 'ごうしつ', translation: 'Счётчик для комнат', kanji: '号室' },
            { kana: 'かい', translation: 'Счётчик для происшествий', kanji: '回' },
            { kana: 'まい', translation: 'Счётчик для тонких плоских вещей', kanji: '枚' },
            { kana: 'めい', translation: 'Счётчик для людей', kanji: '名' },
            { kana: 'ほん, ぽん, ぼん', translation: 'Счётчик длинных объектов', kanji: '本' },
            { kana: '～ぬき', translation: 'Постфикс для фразы "Без ... (чего-нибудь)"', kanji: '～抜き' },
            { kana: 'うけつけ', translation: 'Ресепшен', kanji: '受付' },
            { kana: 'かべ', translation: 'Стена', kanji: '壁' },
            { kana: 'ほこり', translation: 'Гордость', kanji: '誇り' },
            { kana: 'きっぷ', translation: 'Билет (поезд)', kanji: '切符' },
            { kana: 'じゆうせき', translation: 'Незарезервированные места (поезд)', kanji: '自由席' },
            { kana: 'していせき', translation: 'Зарезервированные места (поезд)', kanji: '指定席' },
            { kana: 'おとな', translation: 'Взрослый (человек)', kanji: '大人' },
            { kana: 'かふんしょう', translation: 'Аллергия на пыльцу', kanji: '花粉症' },
            { kana: 'ほこり', translation: 'Грязь, пыль', kanji: '埃' },
            { kana: 'にわ', translation: 'Сад', kanji: '庭' },
            { kana: 'じこしょうかい', translation: 'Self introduction', kanji: '自己紹介' },
            { kana: 'あんない', translation: 'Информация, руководство', kanji: '案内' },
            { kana: 'よやく', translation: 'Бронирование, встреча', kanji: '予約' },
            { kana: 'ほけんしょう', translation: 'Страховая карта', kanji: '保険証' },
            { kana: 'えいぎょう', translation: 'Бизнес, торговля, продажи', kanji: '営業' },
            { kana: 'はつおん', translation: 'Произношение', kanji: '発音' },
            { kana: 'れんらく', translation: 'Общение, контакт', kanji: '連絡' },
            { kana: 'わりかん', translation: 'Разделение стоимости', kanji: '割り勘' },
            { kana: 'おすすめ', translation: 'Рекоммендация', kanji: 'お勧め' },
            { kana: 'まんなか', translation: 'Середина', kanji: '真ん中' },
            { kana: 'なかば', translation: 'Середина (время)', kanji: '半ば' },
            { kana: 'ちょうし', translation: 'Состояние', kanji: '調子' },
            { kana: 'こくせき', translation: 'Национальность', kanji: '国籍' },
            { kana: 'こくない', translation: 'Внутренний, отечественный', kanji: '国内' },
            { kana: 'かがみ', translation: 'Зеркало', kanji: '鏡' },
            { kana: 'もんだい', translation: 'Проблема, вопрос', kanji: '問題' },
            { kana: 'いいわけ', translation: 'Оправдание', kanji: '言い訳' },
            { kana: 'さくひん', translation: 'Работа', kanji: '作品' },
            { kana: 'のろい', translation: 'Проклятье', kanji: '呪い' },
            { kana: 'しんさく', translation: 'Новая работа', kanji: '新作' },
            { kana: 'え', translation: 'Картина', kanji: '絵' },
            { kana: 'びじゅつかん', translation: 'Музей искусства', kanji: '美術館' },
            { kana: 'てんらんかい', translation: 'Выставка', kanji: '展覧会' },
            { kana: 'やくそく', translation: 'Обещание', kanji: '約束' },
            { kana: 'きおく', translation: 'Память', kanji: '記憶' },
            { kana: 'しけん', translation: 'Тест, экзамен', kanji: '試験' },
            { kana: 'えいが', translation: 'Фильм', kanji: '映画' },
            { kana: 'いきかた', translation: 'Маршрут', kanji: '行き方' },
            { kana: 'どうりょう', translation: 'Коллега', kanji: '同僚' },
            { kana: 'せいかい', translation: 'Верный', kanji: '正解' },
            { kana: 'りこん', translation: 'Развод', kanji: '離婚' },
            { kana: 'けっこんしき', translation: 'Свадебная церемония', kanji: '結婚式' },
            { kana: 'けっこん', translation: 'Свадьба', kanji: '結婚' },
            { kana: 'きねんび', translation: 'Годовщина', kanji: '記念日' },
            { kana: 'こうさん', translation: 'Сдача', kanji: '降参' },
            { kana: 'わだい', translation: 'Тема, топик', kanji: '話題' },
            { kana: 'ゆうえんち', translation: 'Парк развлечений', kanji: '遊園地' },
            { kana: 'えがお', translation: 'Улыбка', kanji: '笑顔' },
            { kana: 'かいがい', translation: 'Зарубежный', kanji: '海外' },
            { kana: 'たからくじ', translation: 'Лотеррея', kanji: '宝くじ' },
            { kana: 'じょゆう', translation: 'Актриса', kanji: '女優' },
            { kana: 'はいゆう', translation: 'Актёр', kanji: '俳優' },
            { kana: 'しりあい', translation: 'Знакомый (человек)', kanji: '知り合い' },
            { kana: 'つみ', translation: 'Преступление, грех', kanji: '罪' },
            { kana: 'どくしんしゃ', translation: 'Не женат (холост)', kanji: '独身者' },
            { kana: 'きこんしゃ', translation: 'Женат', kanji: '既婚者' },
            { kana: 'ちゅうし', translation: 'Отменено (что-то запланированное)', kanji: '中止' },
            { kana: 'いなずま', translation: 'Молния', kanji: '稲妻' },
            { kana: 'かみなり', translation: 'Гром', kanji: '雷' },
            { kana: 'しょくぎょう', translation: 'Профессия, занятость', kanji: '職業' },
            { kana: 'ねふだ', translation: 'Ценник', kanji: '値札' },
            { kana: 'びん', translation: 'Рейс, полёт', kanji: '便' },
            { kana: 'ちゃくりく', translation: 'Посадка', kanji: '着陸' },
            { kana: 'ほんき', translation: 'Серьёзность, правда', kanji: '本気' },
            { kana: 'いき', translation: 'Дыхание', kanji: '息' },
            { kana: 'けしき', translation: 'Вид', kanji: '景色' },
            { kana: 'ちょうじょう', translation: 'Вершина', kanji: '頂上' },
            { kana: 'しんじゅ', translation: 'Жемчужина', kanji: '真珠' },
            { kana: 'かいしょう', translation: 'Уменьшение (стреса)', kanji: '解消' },
            { kana: 'きせき', translation: 'Чудо', kanji: '奇跡' },
            { kana: 'もんげん', translation: 'Комендантский час', kanji: '門限' },
            { kana: 'らくしょう', translation: 'Лёгкая победа', kanji: '楽勝' },
            { kana: 'うめあわせ', translation: 'Компенсация', kanji: '埋め合わせ' },
            { kana: 'うちゅう', translation: 'Космос', kanji: '宇宙' },
            { kana: 'じゅんび', translation: 'Подготовка', kanji: '準備' },
            { kana: 'こうかん', translation: 'Менять, обмен', kanji: '交換' },
            { kana: 'じゅうでん', translation: 'Зарядка (батареи)', kanji: '充電' },
            { kana: 'でんち', translation: 'Батарейка', kanji: '電池' },
            { kana: 'じしん', translation: 'Уверенность в себе', kanji: '自信' },
            { kana: 'まんげつ', translation: 'Полнолуние', kanji: '満月' },
            { kana: 'まんぞく', translation: 'Удовлетворенный', kanji: '満足' },
            { kana: 'したみ', translation: 'Предварительный просмотр', kanji: '下見' },
            { kana: 'りかい', translation: 'Понимание', kanji: '理解' },
            { kana: 'ぎじゅつ', translation: 'Умение, мастерство', kanji: '技術' },
            { kana: 'コツ', translation: 'Сноровка, ловкость' },
            { kana: 'けいけん', translation: 'Опыт', kanji: '経験' },
            { kana: 'ついか', translation: 'Дополнение, добавление', kanji: '追加' },
            { kana: 'つゆ', translation: 'Сезон дождей', kanji: '梅雨' },
            { kana: 'つゆいり', translation: 'Начало сезона дождей', kanji: '梅雨入り' },
            { kana: 'つゆあけ', translation: 'Конец сезона дождей', kanji: '梅雨明け' },
            { kana: 'はこ', translation: 'Коробка', kanji: '箱' },
            { kana: 'めいれい', translation: 'Приказ, команда', kanji: '命令' },
        ]
    },
    {
        title: 'Adjectives (い)',
        words: [
            { kana: 'ながい', translation: 'Длинный', kanji: '長い' },
            { kana: 'たかい', translation: 'Высокий', kanji: '高い' },
            { kana: 'みじかい', translation: 'Короткий', kanji: '短い' },
            { kana: 'つよい', translation: 'Сильный', kanji: '強い' },
            { kana: 'よわい', translation: 'Слабый', kanji: '弱い' },
            { kana: 'ちいさい', translation: 'Небольшой', kanji: '小さい' },
            { kana: 'おおきい', translation: 'Большой', kanji: '大きい' },
            { kana: 'はやい', translation: 'Быстрый', kanji: '速い' },
            { kana: 'かわいい', translation: 'Милый', kanji: '可愛い' },
            { kana: 'あまい', translation: 'Сладкий', kanji: '甘い' },
            { kana: 'わかい', translation: 'Молодой', kanji: '若い' },
            { kana: 'ふるい', translation: 'Старый', kanji: '古い' },
            { kana: 'つまらない', translation: 'Скучный', kanji: '詰らない' },
            { kana: 'おもい', translation: 'Тяжёлый', kanji: '重い' },
            { kana: 'ふつう', translation: 'Обычный', kanji: '普通' },
            { kana: 'あたらしい', translation: 'Новый', kanji: '新しい' },
            { kana: 'まっすぐ', translation: 'Прямой', kanji: '真っ直ぐ' },
            { kana: 'おなじ', translation: 'Такой же', kanji: '同じ' },
            { kana: 'すずしい', translation: 'Прохладый (о погоде)', kanji: '涼しい' },
            { kana: 'あたたかい', translation: 'Тёплый (о погоде)', kanji: '温かい' },
            { kana: 'やすい', translation: 'Дешёвый', kanji: '安い' },
            { kana: 'たのしい', translation: 'Весёлый', kanji: '楽しい' },
            { kana: 'おいしい', translation: 'Вкусный', kanji: '美味しい' },
            { kana: 'つめたい', translation: 'Холодный (на ощупь)', kanji: '冷たい' },
            { kana: 'いそがしい', translation: 'Занят', kanji: '忙しい' },
            { kana: 'ちかい', translation: 'Близкий', kanji: '近い' },
            { kana: 'とおい', translation: 'Далёкий', kanji: '遠い' },
            { kana: 'いたい', translation: 'Больно', kanji: '痛い' },
            { kana: 'おもしろい', translation: 'Интересный, забавный', kanji: '面白い' },
            { kana: 'ただしい', translation: 'Правильный', kanji: '正しい' },
            { kana: 'すっぱい', translation: 'Кислый', kanji: '酸っぱい' },
            { kana: 'にがい', translation: 'Горький', kanji: '苦い' },
            { kana: 'せまい', translation: 'Узкий', kanji: '狭い' },
            { kana: 'おそい', translation: 'Медленный, поздний', kanji: '遅い' },
            { kana: 'くらい', translation: 'Тёмный', kanji: '暗い' },
            { kana: 'きたない', translation: 'Грязный', kanji: '汚い' },
            { kana: 'かるい', translation: 'Светлый', kanji: '軽い' },
            { kana: 'からい', translation: 'Горячий, острый', kanji: '辛い' },
            { kana: 'ひろい', translation: 'Широкий', kanji: '広い' },
            { kana: 'ひくい', translation: 'Низкий', kanji: '低い' },
            { kana: 'あかるい', translation: 'Яркий', kanji: '明るい' },
            { kana: 'あぶない', translation: 'Опасный', kanji: '危ない' },
            { kana: 'わるい', translation: 'Плохой', kanji: '悪い' },
            { kana: 'ほそい', translation: 'Худой, тонкий', kanji: '細い' },
            { kana: 'ほしい', translation: 'Желаемый', kanji: '欲しい' },
            { kana: 'いっぱい', translation: 'Полный', kanji: '一杯' },
            { kana: 'こわい', translation: 'Страшный', kanji: '怖い' },
            { kana: 'あつい', translation: 'Жаркий', kanji: '暑い' },
            { kana: 'むしあつい', translation: 'Влажный (погода)', kanji: '蒸し暑い' },
            { kana: 'ふかい', translation: 'Глубокий', kanji: '深い' },
            { kana: 'おとなしい', translation: 'Тихий', kanji: '大人しい' },
            { kana: 'しょっぱい', translation: 'Солёный', kanji: '塩っぱい' },
            { kana: 'うつくしい', translation: 'Красивый', kanji: '美しい' },
            { kana: 'くだらない', translation: 'Бесполезный', kanji: '下らない' },
            { kana: 'さびしい、 さみしい', translation: 'Одинокий', kanji: '寂しい' },
            { kana: 'にぶい', translation: 'Тупой, медленный', kanji: '鈍い' },
            { kana: 'とんでもない', translation: 'Невыносимый' },
            { kana: 'するどい', translation: 'Острый (лезвие)', kanji: '鋭い' },
            { kana: 'やさしい', translation: 'Доброжелательность', kanji: '優しい' },
            { kana: 'やさしい', translation: 'Лёгкий', kanji: '易しい' },
            { kana: 'だるい', translation: 'Истощённый', kanji: '怠い' },
            { kana: 'なつかしい', translation: 'Ностальгический', kanji: '懐かしい' },
            { kana: 'おおい', translation: 'Много, больше', kanji: '多い' },
            { kana: 'むずかしい', translation: 'Сложный', kanji: '難しい' }
        ]
    },
    {
        title: 'Adjectives (な)',
        words: [
            { kana: 'きれい (な)', translation: 'Красивый', kanji: '綺麗 (な)' },
            { kana: 'しずか (な)', translation: 'Спокойный', kanji: '静か (な)' },
            { kana: 'とくべつ (な)', translation: 'Особенный', kanji: '特別 (な)' },
            { kana: 'かんたん (な)', translation: 'Простой', kanji: '簡単 (な)' },
            { kana: 'べんり (な)', translation: 'Удобный', kanji: '便利 (な)' },
            { kana: 'ふべん (な)', translation: 'Неудобный', kanji: '不便 (な)' },
            { kana: 'すてき (な)', translation: 'Хороший, фантастический', kanji: '素敵 (な)' },
            { kana: 'あんぜん (な)', translation: 'Безопасный', kanji: '安全 (な)' },
            { kana: 'だいじ (な)', translation: 'Важный', kanji: '大事 (な)' },
            { kana: 'たいせつ (な)', translation: 'Важный', kanji: '大切 (な)' },
            { kana: 'だめ (な)', translation: 'Нехороший', kanji: '駄目 (な)' },
            { kana: 'ふしんせつ (な)', translation: 'Недобрый', kanji: '不親切 (な)' },
            { kana: 'げんき (な)', translation: 'Хороший', kanji: '元気 (な)' },
            { kana: 'じょうず (な)', translation: 'Умелый', kanji: '上手 (な)' },
            { kana: 'へた (な)', translation: 'Неумелый', kanji: '下手 (な)' },
            { kana: 'ひま (な)', translation: 'Свободный (время)', kanji: '暇 (な)' },
            { kana: 'いろいろ (な)', translation: 'Различный', kanji: '色々 (な)' },
            { kana: 'すき (な)', translation: 'Нравится', kanji: '好き (な)' },
            { kana: 'きらい (な)', translation: 'Несимпатичный (не нравится)', kanji: '嫌い (な)' },
            { kana: 'にぎやか (な)', translation: 'Живой', kanji: '賑やか (な)' },
            { kana: 'しんせつ (な)', translation: 'Добрый', kanji: '親切 (な)' },
            { kana: 'しつれい (な)', translation: 'Грубый', kanji: '失礼 (な)' },
            { kana: 'ゆうめい (な)', translation: 'Известный', kanji: '有名 (な)' },
            { kana: 'むり (な)', translation: 'Невозможный', kanji: '無理 (な)' },
            { kana: 'しょうじき (な)', translation: 'Честный', kanji: '正直 (な)' },
            { kana: 'しんせん (な)', translation: 'Свежий', kanji: '新鮮 (な)' },
            { kana: 'しんけん (な)', translation: 'Серьёзный', kanji: '真剣 (な)' },
            { kana: 'たいへん (な)', translation: 'Трудный, тяжёлый', kanji: '大変 (な)' },
            { kana: 'かわいそう (な)', translation: 'Бедный, жалкий', kanji: '可哀相 (な)' },
            { kana: 'おしゃれ (な)', translation: 'Стильный', kanji: '御洒落 (な)' },
            { kana: 'ていねい (な)', translation: 'Вежливый', kanji: '丁寧 (な)' },
            { kana: 'ぜっこうちょう (な)', translation: 'Восхитительный', kanji: '絶好調 (な)' },
            { kana: 'まあまあ (な)', translation: 'Так себе' },
            { kana: 'ひつよう (な)', translation: 'Необходимый', kanji: '必要 (な)' },
            { kana: 'とくい (な)', translation: 'Сильная сторона (небуквально)', kanji: '得意 (な)' },
            { kana: 'にがて (な)', translation: 'Слабая сторона (небуквально)', kanji: '苦手 (な)' },
            { kana: 'あいまい (な)', translation: 'Неопределенный, неоднозначный', kanji: '曖昧 (な)' },
            { kana: 'まえむき (な)', translation: 'Позитивный', kanji: '前向き (な)' },
            { kana: 'らく (な)', translation: 'Лёгкий', kanji: '楽 (な)' }
        ]
    },
    {
        title: 'Adverbs',
        words: [
            { kana: 'ちょっと', translation: 'Немного' },
            { kana: 'なんて', translation: 'Как (что-то)' },
            { kana: 'うれしい', translation: 'Рад' },
            { kana: 'また', translation: 'Также' },
            { kana: 'こんなふうに', translation: 'Также (like this)' },
            { kana: 'ちょうど', translation: 'Точно' },
            { kana: 'たぶん', translation: 'Вероятно, возможно' },
            { kana: 'でしょう', translation: 'Вероятно, возможно' },
            { kana: 'だけ', translation: 'Только' },
            { kana: 'もちろん', translation: 'Конечно', kanji: '勿論' },
            { kana: 'やさしく', translation: 'Осторожно' },
            { kana: 'あまり', translation: 'Не так много, чуть-чуть' },
            { kana: 'ぜんぜん', translation: 'Вовсе нет', kanji: '全然' },
            { kana: 'ぐらい', translation: 'Примерно (после подсчёта)', kanji: '位' },
            { kana: 'だいたい', translation: 'Примерно (перед подсчётом)' },
            { kana: 'あとで', translation: 'Позже, потом', kanji: '後で' },
            { kana: 'そして', translation: 'Потом' },
            { kana: 'むりょう', translation: 'Бесплатно', kanji: '無料' },
            { kana: 'だって', translation: 'Потому что' },
            { kana: 'まだ', translation: 'Всё ещё (still)' },
            { kana: 'たとえば', translation: 'Например' },
            { kana: 'たくさん', translation: 'Много', kanji: '沢山' },
            { kana: 'ちょう', translation: 'Супер' },
            { kana: 'ぜったいに', translation: 'Определённо, безоговорочно', kanji: '絶対に' },
            { kana: 'きっと', translation: 'Определённо' },
            { kana: 'おかしい', translation: 'Странно, забавно', kanji: '可笑しい' },
            { kana: 'そろそろ', translation: 'Медленно' },
            { kana: 'すぐ', translation: 'Немедленно' },
            { kana: 'まず', translation: 'Прежде всего' },
            { kana: 'じつは', translation: 'На самом деле', kanji: '実は' },
            { kana: 'いっしょに', translation: 'Вместе', kanji: '⼀緒に' },
            { kana: 'べつべつ', translation: 'Раздельно', kanji: '別々' },
            { kana: 'むかし', translation: 'Давно', kanji: '昔' },
            { kana: 'かわりに', translation: 'Вместо', kanji: '代わりに' },
            { kana: 'ぜんぶ', translation: 'Всё', kanji: '全部' },
            { kana: 'てづくり', translation: 'Ручной работы', kanji: '手作り' },
            { kana: 'めちゃめちゃ', translation: 'Очень, супер' },
            { kana: 'あいかわらず', translation: 'Как обычно', kanji: '相変わらず' },
            { kana: 'かなり', translation: 'Значительно', kanji: '可也' },
            { kana: 'なかなか', translation: 'Вполне, очень (превысит ваши ожидания)' },
            { kana: 'のほう', translation: 'В этом направлении (небуквально)', kanji: 'の方' },
            { kana: 'ずっと', translation: 'Всё время' },
            { kana: 'やっぱり', translation: 'Как ожидалось' },
            { kana: 'まったく', translation: 'Невозможно поверить!', kanji: '全く' },
            { kana: 'すべて', translation: 'Полностью, всё', kanji: '全て' },
            { kana: 'おきにいり', translation: 'Любимый', kanji: 'お気に入り' },
            { kana: 'ところで', translation: 'Кстати (by the way)' },
            { kana: 'ずつ', translation: 'Каждый' },
            { kana: 'いじょう', translation: 'Выше (больше, чем)', kanji: '以上' },
            { kana: 'ぴったり', translation: 'Просто, как раз (вовремя)' },
            { kana: 'まっすぐ', translation: 'Прямо', kanji: '真っ直ぐ' },
            { kana: 'ように', translation: 'Подобно' },
            { kana: 'くるしい', translation: 'Тяжело, больно', kanji: '苦しい' },
            { kana: 'ほかに', translation: 'К тому же, кроме того', kanji: '他に' },
            { kana: 'なんとか', translation: 'Как-то (somehow)', kanji: '何とか' },
            { kana: 'なんとなく', translation: 'Почему-то, по какой-то причине', kanji: '何となく' },
            { kana: 'とにかく', translation: 'Во всяком случае, тем не менее' },
            { kana: 'かんりょう', translation: 'Полностью', kanji: '完了' },
            { kana: 'まんまん', translation: 'Полный, наполненный чем-то', kanji: '満々' },
            { kana: 'なによりも', translation: 'Более того', kanji: '何よりも' },
            { kana: 'さらに', translation: 'Более того', kanji: '更に' },
            { kana: 'いきなり', translation: 'Вдруг, внезапно' },
            { kana: '～のなか', translation: 'Между, среди', kanji: '～の中' },
            { kana: 'りょうほう', translation: 'Обе стороны', kanji: '両方' }
        ]
    },
    {
        title: 'Study',
        words: [
            { kana: 'じゅぎょう', translation: 'Урок', kanji: '授業' },
            { kana: 'ごうかく', translation: 'Успех, проход экзамена', kanji: '合格' },
            { kana: 'ふごうかく', translation: 'Неуспех, непроход экзамена', kanji: '不合格' },
            { kana: 'まんてん', translation: 'Полный счёт, идеальный результат', kanji: '満点' },
            { kana: 'れいてん', translation: 'Нулевой счёт, худший результат', kanji: '零点' },
            { kana: 'てんすう', translation: 'Очки, счёт', kanji: '点数' },
            { kana: 'けっか', translation: 'Результат', kanji: '結果' },
            { kana: 'くみ', translation: 'Группа (людей), класс (студентов) и пр.', kanji: '組み' },
            { kana: 'そつぎょう', translation: 'Выпуск (университет/школа)', kanji: '卒業' },
            { kana: 'しゅくだい', translation: 'Домашняя работа', kanji: '宿題' },
            { kana: 'きょうかしょ', translation: 'Тетрадь', kanji: '教科書' }
        ]
    },
    {
        title: 'Questions, places',
        words: [
            { kana: 'どんな', translation: 'Какие? Какого типа?' },
            { kana: 'どちら', translation: 'Который?' },
            { kana: 'どこの', translation: 'Откуда?' },
            { kana: 'どうして', translation: 'Почему? Как?' },
            { kana: 'だれの', translation: 'Чьё?' },
            { kana: 'どのくらい', translation: 'Как долго? Сколько?' }
        ]
    },
    {
        title: 'Locations',
        words: [
            { kana: 'そと', translation: 'Снаружи', kanji: '外' },
            { kana: 'まえ', translation: 'Перед', kanji: '前' },
            { kana: 'うしろ', translation: 'Сзади', kanji: '後ろ' },
            { kana: 'となり', translation: 'Соседний', kanji: '隣' },
            { kana: 'ちかく', translation: 'Поблизости', kanji: '近く' },
            { kana: 'よこ', translation: 'Сторона', kanji: '横' },
            { kana: 'きた', translation: 'Север', kanji: '北' },
            { kana: 'みなみ', translation: 'Юг', kanji: '南' },
            { kana: 'にし', translation: 'Запад', kanji: '西' },
            { kana: 'ひがし', translation: 'Восток', kanji: '東' },
            { kana: 'じっか', translation: 'Родительский дом', kanji: '実家' },
            { kana: 'ふるさと', translation: 'Родной город', kanji: '故郷' },
            { kana: 'しゅと', translation: 'Столица', kanji: '首都' },
            { kana: 'がっこう', translation: 'Школа', kanji: '学校' },
            { kana: 'ぎんこう', translation: 'Банк', kanji: '銀行' },
            { kana: 'くうこう', translation: 'Аэропорт', kanji: '空港' },
            { kana: 'こうえん', translation: 'Парк', kanji: '公園' },
            { kana: 'スーパー', translation: 'Супермаркет' },
            { kana: 'ちゅうしゃじょう', translation: 'Автостоянка', kanji: '駐車場' },
            { kana: 'ばすてい', translation: 'Автобусная астоновка' },
            { kana: 'びょういん', translation: 'Больница', kanji: '病院' },
            { kana: 'りょうりてん', translation: 'Ресторан', kanji: '料理店' },
            { kana: 'げきじょう', translation: 'Театр', kanji: '劇場' },
            { kana: 'たてもの', translation: 'Конструкция, строение', kanji: '建物' }
        ]
    },
    {
        title: 'Technical',
        words: [
            { kana: 'かいしゃ', translation: 'Корпорация', kanji: '会社' },
            { kana: 'でんわ', translation: 'Телефон', kanji: '電話' },
            { kana: 'パソコン', translation: 'Персональный компьютер' },
            { kana: 'けいたいでんわ', translation: 'Мобильный телефон', kanji: '携帯電話' },
            { kana: 'ばんごう', translation: 'Номер', kanji: '番号' }
        ]
    },
    {
        title: 'Relations',
        words: [
            { kana: 'おねえさん', translation: 'Старшая сестра', kanji: 'お姉さん' },
            { kana: 'おとうとさん', translation: 'Младший брат', kanji: '弟さん' },
            { kana: 'いもうとさん', translation: 'Младшая сестра', kanji: '妹さん' },
            { kana: 'むすこさん', translation: 'Сын', kanji: '息子さん' },
            { kana: 'むすめさん', translation: 'Дочь', kanji: '娘さん' },
            { kana: 'まご', translation: 'Внук', kanji: '孫' },
            { kana: 'だんなさん', translation: 'Муж' },
            { kana: 'おくさん', translation: 'Жена', kanji: '奥さん' },
            { kana: 'つま', translation: 'Моя жена' },
            { kana: 'きょうだい', translation: 'Братья и сёстры', kanji: '兄弟' },
            { kana: 'そふ', translation: 'Дедушка', kanji: '祖父' },
            { kana: 'そぼ', translation: 'Бабушка', kanji: '祖母' },
            { kana: 'いとこ', translation: 'Двоюродный' }
        ]
    },
    {
        title: 'Pronouns',
        words: [
            { kana: 'かれらの', translation: 'Их' },
            { kana: 'いっしょに', translation: 'Вместе', kanji: '一緒に' },
            { kana: 'じぶん', translation: 'myself, yourself, him(her)self', kanji: '自分' }
        ]
    },
    {
        title: 'Time',
        words: [
            { kana: 'ごぜん', translation: 'Время с 00:00 до 12:00 (a.m.)' },
            { kana: 'ごご', translation: 'Время с 12:00 до 24:00 (p.m.)' },
            { kana: 'つぎ', translation: 'Следующий', kanji: '次' },
            { kana: 'はん', translation: 'Половина', kanji: '半' },
            { kana: 'にじはん', translation: 'Половина третьего' },
            { kana: 'じゆうじかん', translation: 'Свободные часы' },
            { kana: 'いつから', translation: 'С какого времени?' },
            { kana: 'いまから', translation: 'С этого момента' },
            { kana: 'いつでも', translation: 'В любое время' },
            { kana: 'よく', translation: 'Часто' },
            { kana: 'まいしゅう', translation: 'Каждую неделю', kanji: '毎週' },
            { kana: 'まいつき', translation: 'Каждый месяц', kanji: '毎月' },
            { kana: 'まいたし', translation: 'Каждый год', kanji: '毎年' },
            { kana: 'まいにち', translation: 'Каждый день', kanji: '毎日' },
            { kana: 'ほとんど毎日', translation: 'Практически каждый день', kanji: 'ほとんど毎日' },
            { kana: 'たまに', translation: 'Время от времени' },
            { kana: 'さっき', translation: 'Недавно' },
            { kana: 'いつも', translation: 'Всегда' },
            { kana: 'たいてい', translation: 'В основном', kanji: '大抵' },
            { kana: 'ときどき', translation: 'Иногда', kanji: '時々' },
            { kana: 'おひさしぶり', translation: 'Давно не виделись' },
            { kana: 'とけい', translation: 'Часы', kanji: '時計' },
            { kana: 'とりあえず', translation: 'Для начала' },
            { kana: 'こんど', translation: 'В следующий раз, в другой раз', kanji: '今度' },
            { kana: 'もうすぐ', translation: 'Очень скоро', kanji: 'もう直ぐ' },
            { kana: 'かいえん', translation: 'Время начала выступления', kanji: '開演' },
            { kana: 'びょう', translation: 'Постфикс для секунд', kanji: '秒' },
            { kana: 'さいしょ', translation: 'Первый (порядок)', kanji: '最初' },
            { kana: 'にばんめ', translation: 'Второй (порядок)', kanji: '二番目' },
            { kana: 'けつまつ', translation: 'Конец, заключение', kanji: '結末' },
            { kana: 'けっきょく', translation: 'В конце концов, в конечном счёте', kanji: '結局' },
            { kana: '〜はつの', translation: 'Постфикс: впервые', kanji: '〜初の' },
            { kana: 'さいきん', translation: 'В последнее время', kanji: '最近' },
            { kana: 'げんざい', translation: 'В настоящее время', kanji: '現在' },
            { kana: 'やっと', translation: 'Наконец-то, наконец' },
            { kana: 'いらい', translation: 'С тех пор (since)', kanji: '以来' },
            { kana: 'しょうがつ', translation: 'Новый Год', kanji: '正月' }
        ]
    },
    /*
    {
        title: 'Minutes',
        words: [
            { kana: 'いっぷん', translation: '1 минута', kanji: '一分' },
            { kana: 'にふん', translation: '2 минуты', kanji: '二分' },
            { kana: 'さんぷん', translation: '3 минуты', kanji: '三分' },
            { kana: 'よんぷん', translation: '4 минуты', kanji: '四分' },
            { kana: 'ごふん', translation: '5 минут', kanji: '五分' },
            { kana: 'ろっぷん', translation: '6 минут', kanji: '六分' },
            { kana: 'ななふん', translation: '7 минут', kanji: '七分' },
            { kana: 'はちふん', translation: '8 минут', kanji: '八分' },
            { kana: 'きゅうふん', translation: '9 минут', kanji: '九分' },
            { kana: 'じゅっぷん', translation: '10 минут', kanji: '十分' },
            { kana: 'なんぷん', translation: 'Сколько минут?', kanji: '何分' }
        ]
    },
    */
    {
        title: 'Dates',
        words: [
            { kana: 'たんじょうび', translation: 'День рождения', kanji: '誕生日' },
            { kana: 'あけまして', translation: 'С новым годом', kanji: '明けまして' },

            { kana: 'いつ', translation: 'Когда, время', kanji: '何時' },
            { kana: 'しゅうかん', translation: 'Неделя', kanji: '週間' },

            { kana: 'きのう', translation: 'Вчера', kanji: '昨日' },
            { kana: 'きょう', translation: 'Сегодня', kanji: '今日 ' },
            { kana: 'あした', translation: 'Завтра', kanji: '明日' },
            { kana: 'あさって', translation: 'Послезавтра', kanji: '明後日' },

            { kana: 'せんしゅう', translation: 'Прошлая неделя', kanji: '先週' },
            { kana: 'こんしゅう', translation: 'Текущая неделя', kanji: '今週' },
            { kana: 'らいしゅう', translation: 'Следующая неделя', kanji: '来週' },

            { kana: 'せんげつ', translation: 'Прошлый месяц', kanji: '先月' },
            { kana: 'こんげつ', translation: 'Текущий месяц', kanji: '今月' },
            { kana: 'らいげつ', translation: 'Следующий месяц', kanji: '来月' },

            { kana: 'きょねん', translation: 'В прошлом году', kanji: '去年' },
            { kana: 'ことし', translation: 'В этом году', kanji: '今年' },
            { kana: 'らいねん', translation: 'В следующем году', kanji: '来年' },

            { kana: 'そのあと', translation: 'После этого', kanji: 'その後' },
            { kana: 'ひる', translation: 'День', kanji: '昼' },
            { kana: 'ばん', translation: 'Вечер', kanji: '晩' },
            { kana: 'よる', translation: 'Ночь', kanji: '夜' },

            { kana: 'げつようび', translation: 'Понедельник', kanji: '月曜日' },
            { kana: 'かようび', translation: 'Вторник', kanji: '火曜日' },
            { kana: 'すいようび', translation: 'Среда', kanji: '水曜日' },
            { kana: 'もくようび', translation: 'Четверг', kanji: '木曜日' },
            { kana: 'きんようび', translation: 'Пятница', kanji: '金曜日' },
            { kana: 'どようび', translation: 'Суббота', kanji: '土曜日' },
            { kana: 'にちようび', translation: 'Воскресенье', kanji: '日曜日' },
            { kana: 'なんようび', translation: 'Какой день недели?', kanji: '何曜日' },
            { kana: 'へいじつ', translation: 'Будние дни', kanji: '平日' },
            { kana: 'しゅうまつ', translation: 'Выходные дни', kanji: '週末' },

            { kana: 'ついたち', translation: '1 число', kanji: '一日' },
            { kana: 'ふつか', translation: '2 число', kanji: '二日' },
            { kana: 'みっか', translation: '3 число', kanji: '三日' },
            { kana: 'よっか', translation: '4 число', kanji: '四日' },
            { kana: 'いつか', translation: '5 число', kanji: '五日' },
            { kana: 'むいか', translation: '6 число', kanji: '六日' },
            { kana: 'なのか', translation: '7 число', kanji: '七日' },
            { kana: 'ようか', translation: '8 число', kanji: '八日' },
            { kana: 'ここのか', translation: '9 число', kanji: '九日' },
            { kana: 'とおか', translation: '10 число', kanji: '十日' },
            { kana: 'はつか', translation: '20 число', kanji: '二十日' },
            { kana: 'みそか', translation: '30 число', kanji: '三十日' }
        ]
    },
    {
        title: 'Counters. General',
        words: [
            { kana: 'ひとつ', translation: 'Один', kanji: '一つ' },
            { kana: 'ふたつ', translation: 'Два', kanji: '二つ' },
            { kana: 'みっつ', translation: 'Три', kanji: '三つ' },
            { kana: 'よっつ', translation: 'Четыре', kanji: '四つ' },
            { kana: 'いつつ', translation: 'Пять', kanji: '五つ' },
            { kana: 'むっつ', translation: 'Шесть', kanji: '六つ' },
            { kana: 'ななつ', translation: 'Семь', kanji: '七つ' },
            { kana: 'やっつ', translation: 'Восемь', kanji: '八つ' },
            { kana: 'ここのつ', translation: 'Девять', kanji: '九つ' },
            { kana: 'とお', translation: 'Десять', kanji: '十つ' },
            { kana: 'いくつ', translation: 'Сколько?', kanji: '幾つ' }
        ]
    },
    {
        title: 'Counters. Floors',
        words: [
            { kana: 'いっかい', translation: '1 этаж', kanji: '一階' },
            { kana: 'にかい', translation: '2 этаж', kanji: '二階' },
            { kana: 'さんかい、さんがい', translation: '3 этаж', kanji: '三階' },
            { kana: 'よんかい', translation: '4 этаж', kanji: '四階' },
            { kana: 'ごかい', translation: '5 этаж', kanji: '五階' },
            { kana: 'ろっかい', translation: '6 этаж', kanji: '六階' },
            { kana: 'ななかい', translation: '7 этаж', kanji: '七階' },
            { kana: 'はっかい', translation: '8 этаж', kanji: '八階' },
            { kana: 'きゅうかい', translation: '9 этаж', kanji: '九階' },
            { kana: 'じゅうかい', translation: '10 этаж', kanji: '十階' },
            { kana: 'じゅういっかい', translation: '11 этаж', kanji: '十一階' },
            { kana: 'じゅうにかい', translation: '12 этаж', kanji: '十二階' },
            { kana: 'なんかい、なんがい', translation: 'Какой этаж?', kanji: '何階' }
        ]
    },
    {
        title: 'Age Numbers',
        words: [
            { kana: 'いっさい', translation: '1 год', kanji: '一歳' },
            { kana: 'にさい', translation: '2 года', kanji: '二歳' },
            { kana: 'さんさい', translation: '3 года', kanji: '三歳' },
            { kana: 'よんさい', translation: '4 года', kanji: '四歳' },
            { kana: 'ごさい', translation: '5 лет', kanji: '五歳' },
            { kana: 'ろくさい', translation: '6 лет', kanji: '六歳' },
            { kana: 'ななさい', translation: '7 лет', kanji: '七歳' },
            { kana: 'はっさい', translation: '8 лет', kanji: '八歳' },
            { kana: 'きゅうさい', translation: '9 лет', kanji: '九歳' },
            { kana: 'じゅっさい', translation: '10 лет', kanji: '十歳' },
            { kana: 'じゅいっさい', translation: '11 лет', kanji: '十一歳' },
            { kana: 'はたち', translation: '20 лет', kanji: '二十歳' },
            { kana: 'にじゅうっさい', translation: '21 год', kanji: '二十一歳' }
        ]
    },
    {
        title: 'Roles',
        words: [
            { kana: 'けいさつかん', translation: 'Офицер полиции', kanji: '警察官' },
            { kana: 'りゅうがくせい', translation: 'Студент по обмену', kanji: '留学生' },
            { kana: 'がくせい', translation: 'Студент', kanji: '学生' },
            { kana: 'せいと', translation: 'Студент', kanji: '生徒' },
            { kana: 'せんこう', translation: 'Специальность', kanji: '専攻' },
            { kana: 'つうこうにん', translation: 'Прохожий', kanji: '通行人' },
            { kana: 'すうがく', translation: 'Математика', kanji: '数学' },
            { kana: 'ちり', translation: 'География', kanji: '地理' },
            { kana: 'れきし', translation: 'История', kanji: '歴史' },
            { kana: 'かがく', translation: 'Химия', kanji: '化学' },
            { kana: 'けいざい', translation: 'Экономия, экономика', kanji: '経済' },
            { kana: 'せんもんか', translation: 'Специалист', kanji: '専門家' },
            { kana: 'はかせ', translation: 'Доктор (наук)', kanji: '博士' },
            { kana: 'おたく', translation: 'Человек, одержимый чем-то' },
            { kana: 'にんきもの', translation: 'Популярная персона', kanji: '⼈気者' },
            { kana: '犯人', translation: 'Преступник, виновный', kanji: 'はんにん' },
            { kana: 'はずかしがりや', translation: 'Стеснительный человек', kanji: '恥ずかしがり屋' }
        ]
    },
    {
        title: 'Body parts',
        words: [
            { kana: 'あたま', translation: 'Голова', kanji: '頭' },
            { kana: 'かみ', translation: 'Волосы, причёска' },
            { kana: 'こえ', translation: 'Голос', kanji: '声' },
            { kana: 'き', translation: 'Чувство', kanji: '気' },
            { kana: 'かお', translation: 'Лицо', kanji: '顔' },
            { kana: 'うで', translation: 'Рука (arm)', kanji: '腕' },
            { kana: 'はな', translation: 'Нос', kanji: '鼻' },
            { kana: 'くちびる', translation: 'Губы', kanji: '唇' },
            { kana: 'は', translation: 'Зуб', kanji: '歯' },
            { kana: 'のど', translation: 'Горло' },
            { kana: 'かた', translation: 'Плечо', kanji: '肩' },
            { kana: 'せなか', translation: 'Спина', kanji: '背中' },
            { kana: 'おなか', translation: 'Живот', kanji: 'お腹' },
            { kana: 'むね', translation: 'Грудь', kanji: '胸' },
            { kana: 'ひざ', translation: 'Колено', kanji: '膝' },
            { kana: 'ゆび', translation: 'Палец', kanji: '指' },
            { kana: 'せ', translation: 'Рост', kanji: '背' },
            { kana: 'しんちょう', translation: 'Высота тела', kanji: '身長' },
            { kana: 'みみ', translation: 'Ухо', kanji: '耳' },
            { kana: 'はい', translation: 'Лёгкие', kanji: '肺' }
        ]
    },
    {
        title: 'Combinations',
        words: [
            { kana: 'それとも', translation: 'Или' },
            { kana: 'それから', translation: 'И, и также' }
        ]
    },
    {
        title: 'Phrases',
        words: [
            { kana: 'おじゃまします', translation: 'Жаль беспокоить вас (когда входишь или покидаешь чужой дом)' },
            { kana: 'おまたせしました', translation: 'Простите, что заставили ждать' },
            { kana: 'こちそうさまでした', translation: 'Спасибо за еду' },
            { kana: 'かんけいない', translation: 'Не имеет значения' },
            { kana: 'おつかれさま', translation: 'Спасибо, достаточно на сегодня, привет (на работе)' },
            { kana: 'これでいい', translation: 'Это хорошо' },
            { kana: 'どうしましたか', translation: 'Что случилось?' },
            { kana: 'おかげさまで', translation: 'Благодарен вам' },
            { kana: 'こちらこそ', translation: 'То же самое и я' },
            { kana: 'けっこう', translation: 'Нет, спасибо', kanji: '結構' },
            { kana: 'おせわになりました', translation: 'Спасибо за вашу доброту', kanji: 'お世話になりました' },
            { kana: 'じゃくにくきょうしょく', translation: 'Выживает сильнейший', kanji: '弱肉強食' },
            { kana: 'いちごいちえ', translation: 'Единственный в жизни шанс', kanji: '一期一会' },
            { kana: 'ものたりない', translation: 'Чего-то не хватает, недостаточно', kanji: '物足りない' },
            { kana: 'しじょうはつ', translation: 'Первый в истории', kanji: '史上初' },
            { kana: 'きがかわりました', translation: 'Изменилось мнение', kanji: '気が変わりました' },
            { kana: 'あんぜんだいいち', translation: 'Безопасность прежде всего', kanji: '安全第⼀' },
            { kana: 'やるき', translation: 'Желание (сделать что-то)', kanji: 'やる気' },
            { kana: 'やるきがない', translation: 'Нежелание (делать что-то)', kanji: 'やる気がない' },
            { kana: 'やるきになる', translation: 'Стать мотивированным', kanji: 'やる気になる' },
            { kana: 'やるきありますか', translation: 'У тебя есть мотивация (мотивировать кого-то)', kanji: 'やる気ありますか' },
            { kana: 'しやがせまい', translation: 'Иметь узкое представление о вещах', kanji: '視野が狭い' },
            { kana: 'しやがひろい', translation: 'Иметь широкое представление о вещах', kanji: '視野が広い' },
            { kana: 'かんべんしてください', translation: 'Оставьте меня в покое, пожалуйста', kanji: '勘弁してください' }
        ]
    },
    {
        title: 'Activities',
        words: [
            { kana: 'すもぐり', translation: 'Дайвинг без оборудования', kanji: '素潜り' }
        ]
    },
    {
        title: 'Medicine',
        words: [
            { kana: 'くすり', translation: 'Медицина', kanji: '薬' },
            { kana: 'かぜ', translation: 'Простуда', kanji: '風邪' },
            { kana: 'しんさつ', translation: 'Медицинская консультация', kanji: '診察' },
            { kana: 'はきけ', translation: 'Тошнота', kanji: '吐き気' },
            { kana: 'ねつ', translation: 'Зной, температура', kanji: '熱' },
            { kana: 'ど', translation: 'Степень, температура', kanji: '度' },
            { kana: 'かんごし', translation: 'Медсестра, медбрат', kanji: '看護師' },
            { kana: 'やっきょく', translation: 'Аптека', kanji: '薬局' }
        ]
    },
    {
        title: 'Money',
        words: [
            { kana: 'ぜい', translation: 'Налог', kanji: '税' },
            { kana: 'ぜいこみ', translation: 'Налог включён', kanji: '税込み' },
            { kana: 'げんきん', translation: 'Наличные', kanji: '現金' },
            { kana: 'かかく', translation: 'Цена', kanji: '価格' },
            { kana: 'かいけい', translation: 'Счёт, чек', kanji: '会計' },
            { kana: 'たま', translation: 'Монета, мячик', kanji: '玉' },
            { kana: 'さつ', translation: 'Банкнота', kanji: '札' },
            { kana: 'りょうしゅうしょ', translation: 'Квитанция', kanji: '領収書' },
            { kana: 'おつり', translation: 'Сдача' },
            { kana: 'しょほうせん', translation: 'Рецепт', kanji: '処方箋' },
            { kana: 'ちょきん', translation: 'Сбережения', kanji: '貯金' },
            { kana: 'ねんしゅう', translation: 'Годовая зарплата', kanji: '年収' },
            { kana: 'げっしゅう', translation: 'Месячная зарплата', kanji: '月収' },
            { kana: 'しゅうにゅう', translation: 'Прибыль', kanji: '収入' },
            { kana: 'ねだん', translation: 'Цена, стоимость', kanji: '値段' }
        ]
    },
    {
        title: 'Food',
        words: [
            { kana: 'もちかえり', translation: 'Взять с собой' },
            { kana: 'てんない', translation: 'В магазине' },
            { kana: 'おにぎり', translation: 'Рисовый шарик', kanji: 'お握り' },
            { kana: 'ひるごはん', translation: 'Обед', kanji: '昼ご飯' },
            { kana: 'おかし', translation: 'Конфета', kanji: 'お菓子' },
            { kana: 'やさい', translation: 'Овощи', kanji: '野菜' },
            { kana: 'さしみ', translation: 'Порезанная рыба', kanji: '刺身' },
            { kana: 'しお', translation: 'Соль', kanji: '塩' },
            { kana: 'はい', translation: 'Кружка', kanji: '杯' },
            { kana: 'からあげ', translation: 'Жареная курица' },
            { kana: 'かつどん', translation: 'Жареная свинина в панировке и рис', kanji: 'カツ丼' },
            { kana: 'とんかつ', translation: 'Свиная котлета', kanji: '豚カツ' },
            { kana: 'ていしょく', translation: 'Комплексное блюдо дня', kanji: '定食' },
            { kana: 'おおもり', translation: 'Большая порция', kanji: '大盛り' },
            { kana: 'しょうゆ', translation: 'Соевый соус' },
            { kana: 'あさめしまえ', translation: 'Кусок торта', kanji: '朝飯前' },
            { kana: 'やきとり', translation: 'Курица на грилле', kanji: '焼き鳥' },
            { kana: 'やきにく', translation: 'Мясо на барбекю', kanji: '焼肉' },
            { kana: 'しょくせいかつ', translation: 'Стиль питания', kanji: '食生活' },
            { kana: 'のり', translation: 'Морские водоросли', kanji: '海苔' },
            { kana: 'ピーマン', translation: 'Зелёный перец' },
            { kana: 'なす', translation: 'Баклажан', kanji: '茄子' },
            { kana: 'にんにく', translation: 'Чеснок' }
        ]
    },
    /*
    {
        title: 'Class 1 verbs. When ます is preceded by -i',
        words: [
            { kana: 'あいます', translation: 'あう' },
            { kana: 'いきます', translation: 'いく' },
            { kana: 'はなします', translation: 'はなす' },
            { kana: 'のみます', translation: 'のむ' },
            { kana: 'まちます', translation: 'まつ' },
            { kana: 'あります', translation: 'ある' }
        ]
    },
    {
        title: 'Class 2 verbs. When ます is preceded by -e or a one syllable sound',
        words: [
            { kana: 'たべます', translation: 'たべる' },
            { kana: 'みます', translation: 'みる' },
            { kana: 'ねます', translation: 'ねる' }
        ]
    },
    {
        title: 'Class 3 verbs.',
        words: [
            { kana: 'します', translation: 'する' },
            { kana: 'きます', translation: 'くる' }
        ]
    }
    */
];
